"""
Physics domain enum generated from LinkML schema.

DO NOT EDIT THIS FILE DIRECTLY.
Edit imas_codex/definitions/physics/domains.yaml and run:
    uv run gen-physics-domains

Generated: 2025-12-17T21:50:50.470800+00:00
Schema: physics_domains
"""

from enum import Enum


class PhysicsDomain(str, Enum):
    """Physics domains for categorizing IMAS Interface Data Structures (IDS).

    Each domain represents a distinct area of fusion plasma physics or
    tokamak engineering. This enum is generated from the LinkML schema
    at definitions/physics/domains.yaml.
    """

    EQUILIBRIUM = "equilibrium"  # MHD equilibrium and magnetic field configuration
    TRANSPORT = "transport"  # Particle, energy, and momentum transport
    MHD = "mhd"  # Magnetohydrodynamic instabilities and modes
    TURBULENCE = "turbulence"  # Microscopic turbulence and anomalous transport
    HEATING = "heating"  # Auxiliary heating systems (NBI, ICRH, ECRH)
    CURRENT_DRIVE = "current_drive"  # Non-inductive current drive methods
    WALL = "wall"  # Plasma-wall interactions and first wall components
    DIVERTOR = "divertor"  # Divertor physics and power exhaust
    EDGE_PHYSICS = "edge_physics"  # Edge and scrape-off layer physics
    PARTICLE_DIAGNOSTICS = (
        "particle_diagnostics"  # Particle measurement and analysis systems
    )
    ELECTROMAGNETIC_DIAGNOSTICS = (
        "electromagnetic_diagnostics"  # Electromagnetic wave and field diagnostics
    )
    RADIATION_DIAGNOSTICS = (
        "radiation_diagnostics"  # Radiation-based diagnostic systems
    )
    MAGNETIC_DIAGNOSTICS = "magnetic_diagnostics"  # Magnetic field measurement systems
    MECHANICAL_DIAGNOSTICS = (
        "mechanical_diagnostics"  # Mechanical and pressure measurement systems
    )
    CONTROL = "control"  # Plasma control and feedback systems
    OPERATIONAL = "operational"  # Operational parameters and machine status
    COILS = "coils"  # Magnetic coil systems and field generation
    STRUCTURE = "structure"  # Structural components and mechanical systems
    SYSTEMS = "systems"  # Engineering systems and plant components
    DATA_MANAGEMENT = (
        "data_management"  # Data organization, metadata, and information management
    )
    WORKFLOW = "workflow"  # Computational workflows and process management
    GENERAL = "general"  # General purpose or uncategorized data structures
