"""
Physics domain enum generated from LinkML schema.

DO NOT EDIT THIS FILE DIRECTLY.
Edit imas_codex/definitions/physics/domains.yaml and run:
    uv run gen-physics-domains

Generated: 2025-12-17T22:12:34.164222+00:00
Schema: physics_domains
"""

from enum import Enum


class PhysicsDomain(str, Enum):
    """Physics domains for categorizing IMAS Interface Data Structures (IDS).

    Each domain represents a distinct area of fusion plasma physics or
    tokamak engineering. This enum is generated from the LinkML schema
    at definitions/physics/domains.yaml.
    """

    EQUILIBRIUM = "equilibrium"  # Magnetohydrodynamic equilibrium and magnetic field configuration
    TRANSPORT = "transport"  # Particle, energy, and momentum transport processes
    MAGNETOHYDRODYNAMICS = (
        "magnetohydrodynamics"  # Magnetohydrodynamic instabilities and plasma modes
    )
    TURBULENCE = (
        "turbulence"  # Microscopic turbulence and anomalous transport phenomena
    )
    AUXILIARY_HEATING = "auxiliary_heating"  # Auxiliary heating systems including neutral beam injection and radiofrequency heating
    CURRENT_DRIVE = "current_drive"  # Non-inductive current drive methods
    PLASMA_WALL_INTERACTIONS = (
        "plasma_wall_interactions"  # Plasma-wall interactions and first wall components
    )
    DIVERTOR_PHYSICS = (
        "divertor_physics"  # Divertor physics and power exhaust mechanisms
    )
    EDGE_PLASMA_PHYSICS = (
        "edge_plasma_physics"  # Edge plasma and scrape-off layer physics
    )
    PARTICLE_MEASUREMENT_DIAGNOSTICS = "particle_measurement_diagnostics"  # Particle measurement and analysis diagnostic systems
    ELECTROMAGNETIC_WAVE_DIAGNOSTICS = "electromagnetic_wave_diagnostics"  # Electromagnetic wave and field diagnostic systems
    RADIATION_MEASUREMENT_DIAGNOSTICS = (
        "radiation_measurement_diagnostics"  # Radiation-based diagnostic systems
    )
    MAGNETIC_FIELD_DIAGNOSTICS = (
        "magnetic_field_diagnostics"  # Magnetic field measurement diagnostic systems
    )
    MECHANICAL_MEASUREMENT_DIAGNOSTICS = "mechanical_measurement_diagnostics"  # Mechanical and pressure measurement diagnostic systems
    PLASMA_CONTROL = "plasma_control"  # Plasma control and feedback systems
    MACHINE_OPERATIONS = (
        "machine_operations"  # Operational parameters and machine status monitoring
    )
    MAGNETIC_FIELD_SYSTEMS = "magnetic_field_systems"  # Magnetic field coil systems and field generation equipment
    STRUCTURAL_COMPONENTS = (
        "structural_components"  # Structural components and mechanical systems
    )
    PLANT_SYSTEMS = (
        "plant_systems"  # Engineering plant systems and auxiliary components
    )
    DATA_MANAGEMENT = (
        "data_management"  # Data organization, metadata, and information management
    )
    COMPUTATIONAL_WORKFLOW = (
        "computational_workflow"  # Computational workflows and process management
    )
    GENERAL = "general"  # General purpose or uncategorized data structures
