"""
Discovery Engine Pydantic Models - Data.

AUTO-GENERATED from imas_codex/ontology/discovery/data.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-discovery-models --force
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "discovery",
        "default_range": "string",
        "description": "Schema for data exploration artifacts. Captures MDSplus "
        "configuration, HDF5/NetCDF patterns, and data organization.",
        "id": "https://iter.org/imas-codex/discovery/data",
        "imports": ["linkml:types"],
        "name": "discovery_data",
        "prefixes": {
            "discovery": {
                "prefix_prefix": "discovery",
                "prefix_reference": "https://iter.org/imas-codex/discovery/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex/imas_codex/ontology/discovery/data.yaml",
        "title": "Data Discovery Schema",
    }
)


class DataArtifact(ConfiguredBaseModel):
    """
    Data access and organization patterns for a facility. Supports partial updates for incremental discovery.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    facility: str = Field(
        default=...,
        description="""Facility identifier (e.g., epfl, jet, iter)""",
        json_schema_extra={
            "linkml_meta": {"alias": "facility", "domain_of": ["DataArtifact"]}
        },
    )
    explored_at: datetime = Field(
        default=...,
        description="""Timestamp when this artifact was created""",
        json_schema_extra={
            "linkml_meta": {"alias": "explored_at", "domain_of": ["DataArtifact"]}
        },
    )
    mdsplus: MDSplusInfo | None = Field(
        default=None,
        description="""MDSplus configuration and trees""",
        json_schema_extra={
            "linkml_meta": {"alias": "mdsplus", "domain_of": ["DataArtifact"]}
        },
    )
    hdf5: HDF5Info | None = Field(
        default=None,
        description="""HDF5 data patterns""",
        json_schema_extra={
            "linkml_meta": {"alias": "hdf5", "domain_of": ["DataArtifact"]}
        },
    )
    netcdf: NetCDFInfo | None = Field(
        default=None,
        description="""NetCDF data patterns""",
        json_schema_extra={
            "linkml_meta": {"alias": "netcdf", "domain_of": ["DataArtifact"]}
        },
    )
    data_formats: list[DataFormatInfo] | None = Field(
        default=None,
        description="""Other data formats found""",
        json_schema_extra={
            "linkml_meta": {"alias": "data_formats", "domain_of": ["DataArtifact"]}
        },
    )
    shot_ranges: list[ShotRange] | None = Field(
        default=None,
        description="""Known shot number ranges""",
        json_schema_extra={
            "linkml_meta": {"alias": "shot_ranges", "domain_of": ["DataArtifact"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Freeform observations about data organization""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


class MDSplusInfo(ConfiguredBaseModel):
    """
    MDSplus data system configuration
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    available: bool = Field(
        default=...,
        description="""Whether MDSplus is accessible""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "available",
                "domain_of": ["MDSplusInfo", "HDF5Info", "NetCDFInfo"],
            }
        },
    )
    server: str | None = Field(
        default=None,
        description="""MDSplus server hostname""",
        json_schema_extra={
            "linkml_meta": {"alias": "server", "domain_of": ["MDSplusInfo"]}
        },
    )
    trees: list[str] | None = Field(
        default=None,
        description="""Available MDSplus tree names""",
        json_schema_extra={
            "linkml_meta": {"alias": "trees", "domain_of": ["MDSplusInfo"]}
        },
    )
    default_tree: str | None = Field(
        default=None,
        description="""Default tree for this facility""",
        json_schema_extra={
            "linkml_meta": {"alias": "default_tree", "domain_of": ["MDSplusInfo"]}
        },
    )
    python_bindings: bool | None = Field(
        default=None,
        description="""Whether Python MDSplus bindings work""",
        json_schema_extra={
            "linkml_meta": {"alias": "python_bindings", "domain_of": ["MDSplusInfo"]}
        },
    )
    example_signals: list[str] | None = Field(
        default=None,
        description="""Example signal paths that work""",
        json_schema_extra={
            "linkml_meta": {"alias": "example_signals", "domain_of": ["MDSplusInfo"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about MDSplus setup""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


class HDF5Info(ConfiguredBaseModel):
    """
    HDF5 data patterns and locations
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    available: bool = Field(
        default=...,
        description="""Whether HDF5 files are present""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "available",
                "domain_of": ["MDSplusInfo", "HDF5Info", "NetCDFInfo"],
            }
        },
    )
    locations: list[str] | None = Field(
        default=None,
        description="""Paths where HDF5 files are found""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "locations",
                "domain_of": ["HDF5Info", "NetCDFInfo", "DataFormatInfo"],
            }
        },
    )
    naming_patterns: list[str] | None = Field(
        default=None,
        description="""File naming conventions observed""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "naming_patterns",
                "domain_of": ["HDF5Info", "NetCDFInfo"],
            }
        },
    )
    h5dump_available: bool | None = Field(
        default=None,
        description="""Whether h5dump tool is available""",
        json_schema_extra={
            "linkml_meta": {"alias": "h5dump_available", "domain_of": ["HDF5Info"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about HDF5 usage""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


class NetCDFInfo(ConfiguredBaseModel):
    """
    NetCDF data patterns and locations
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    available: bool = Field(
        default=...,
        description="""Whether NetCDF files are present""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "available",
                "domain_of": ["MDSplusInfo", "HDF5Info", "NetCDFInfo"],
            }
        },
    )
    locations: list[str] | None = Field(
        default=None,
        description="""Paths where NetCDF files are found""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "locations",
                "domain_of": ["HDF5Info", "NetCDFInfo", "DataFormatInfo"],
            }
        },
    )
    naming_patterns: list[str] | None = Field(
        default=None,
        description="""File naming conventions observed""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "naming_patterns",
                "domain_of": ["HDF5Info", "NetCDFInfo"],
            }
        },
    )
    ncdump_available: bool | None = Field(
        default=None,
        description="""Whether ncdump tool is available""",
        json_schema_extra={
            "linkml_meta": {"alias": "ncdump_available", "domain_of": ["NetCDFInfo"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about NetCDF usage""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


class DataFormatInfo(ConfiguredBaseModel):
    """
    Information about a data format
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    name: str = Field(
        default=...,
        description="""Format name (e.g., CSV, JSON, MAT, IDL)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["DataFormatInfo", "ShotRange"],
            }
        },
    )
    extension: str | None = Field(
        default=None,
        description="""File extension""",
        json_schema_extra={
            "linkml_meta": {"alias": "extension", "domain_of": ["DataFormatInfo"]}
        },
    )
    locations: list[str] | None = Field(
        default=None,
        description="""Paths where this format is found""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "locations",
                "domain_of": ["HDF5Info", "NetCDFInfo", "DataFormatInfo"],
            }
        },
    )
    description: str | None = Field(
        default=None,
        description="""What this format is used for""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["DataFormatInfo", "ShotRange"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about this format""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


class ShotRange(ConfiguredBaseModel):
    """
    A range of shot numbers
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/data"}
    )

    name: str | None = Field(
        default=None,
        description="""Name or description of this range""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["DataFormatInfo", "ShotRange"],
            }
        },
    )
    start: int | None = Field(
        default=None,
        description="""First shot number""",
        json_schema_extra={
            "linkml_meta": {"alias": "start", "domain_of": ["ShotRange"]}
        },
    )
    end: int | None = Field(
        default=None,
        description="""Last shot number (or current)""",
        json_schema_extra={"linkml_meta": {"alias": "end", "domain_of": ["ShotRange"]}},
    )
    description: str | None = Field(
        default=None,
        description="""What this shot range represents""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["DataFormatInfo", "ShotRange"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about this shot range""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "DataArtifact",
                    "MDSplusInfo",
                    "HDF5Info",
                    "NetCDFInfo",
                    "DataFormatInfo",
                    "ShotRange",
                ],
            }
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
DataArtifact.model_rebuild()
MDSplusInfo.model_rebuild()
HDF5Info.model_rebuild()
NetCDFInfo.model_rebuild()
DataFormatInfo.model_rebuild()
ShotRange.model_rebuild()
