"""
Discovery Engine Pydantic Models - Environment.

AUTO-GENERATED from imas_codex/ontology/discovery/environment.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-discovery-models --force
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "discovery",
        "default_range": "string",
        "description": "Schema for environment exploration artifacts. Captures Python "
        "installation, operating system, compilers, and environment "
        "module system information.",
        "id": "https://iter.org/imas-codex/discovery/environment",
        "imports": ["linkml:types"],
        "name": "discovery_environment",
        "prefixes": {
            "discovery": {
                "prefix_prefix": "discovery",
                "prefix_reference": "https://iter.org/imas-codex/discovery/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex/imas_codex/ontology/discovery/environment.yaml",
        "title": "Environment Discovery Schema",
    }
)


class EnvironmentArtifact(ConfiguredBaseModel):
    """
    Environment snapshot from facility exploration. Supports partial updates - each field is optional for incremental discovery.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/environment"}
    )

    facility: str = Field(
        default=...,
        description="""Facility identifier (e.g., epfl, jet, iter)""",
        json_schema_extra={
            "linkml_meta": {"alias": "facility", "domain_of": ["EnvironmentArtifact"]}
        },
    )
    explored_at: datetime = Field(
        default=...,
        description="""Timestamp when this artifact was created""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "explored_at",
                "domain_of": ["EnvironmentArtifact"],
            }
        },
    )
    python: PythonInfo | None = Field(
        default=None,
        description="""Python installation details""",
        json_schema_extra={
            "linkml_meta": {"alias": "python", "domain_of": ["EnvironmentArtifact"]}
        },
    )
    os: OSInfo | None = Field(
        default=None,
        description="""Operating system information""",
        json_schema_extra={
            "linkml_meta": {"alias": "os", "domain_of": ["EnvironmentArtifact"]}
        },
    )
    compilers: list[CompilerInfo] | None = Field(
        default=None,
        description="""Available compilers on the system""",
        json_schema_extra={
            "linkml_meta": {"alias": "compilers", "domain_of": ["EnvironmentArtifact"]}
        },
    )
    module_system: ModuleSystemInfo | None = Field(
        default=None,
        description="""Environment module system (Lmod, Environment Modules)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "module_system",
                "domain_of": ["EnvironmentArtifact"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Freeform observations about the environment""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "EnvironmentArtifact",
                    "PythonInfo",
                    "OSInfo",
                    "CompilerInfo",
                    "ModuleSystemInfo",
                ],
            }
        },
    )


class PythonInfo(ConfiguredBaseModel):
    """
    Python installation details
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/environment"}
    )

    version: str = Field(
        default=...,
        description="""Python version string (e.g., 3.9.21)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": ["PythonInfo", "OSInfo", "CompilerInfo"],
            }
        },
    )
    path: str = Field(
        default=...,
        description="""Absolute path to Python binary""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["PythonInfo", "CompilerInfo"],
            }
        },
    )
    packages: list[str] | None = Field(
        default=None,
        description="""Installed Python packages (format name==version)""",
        json_schema_extra={
            "linkml_meta": {"alias": "packages", "domain_of": ["PythonInfo"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about Python environment""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "EnvironmentArtifact",
                    "PythonInfo",
                    "OSInfo",
                    "CompilerInfo",
                    "ModuleSystemInfo",
                ],
            }
        },
    )


class OSInfo(ConfiguredBaseModel):
    """
    Operating system information
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/environment"}
    )

    name: str = Field(
        default=...,
        description="""OS distribution name (e.g., RHEL, Ubuntu, CentOS)""",
        json_schema_extra={
            "linkml_meta": {"alias": "name", "domain_of": ["OSInfo", "CompilerInfo"]}
        },
    )
    version: str = Field(
        default=...,
        description="""OS version (e.g., 9.6, 22.04)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": ["PythonInfo", "OSInfo", "CompilerInfo"],
            }
        },
    )
    kernel: str | None = Field(
        default=None,
        description="""Kernel version string""",
        json_schema_extra={"linkml_meta": {"alias": "kernel", "domain_of": ["OSInfo"]}},
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about operating system""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "EnvironmentArtifact",
                    "PythonInfo",
                    "OSInfo",
                    "CompilerInfo",
                    "ModuleSystemInfo",
                ],
            }
        },
    )


class CompilerInfo(ConfiguredBaseModel):
    """
    Compiler installation details
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/environment"}
    )

    name: str = Field(
        default=...,
        description="""Compiler name (e.g., gcc, gfortran, icx, ifx)""",
        json_schema_extra={
            "linkml_meta": {"alias": "name", "domain_of": ["OSInfo", "CompilerInfo"]}
        },
    )
    version: str | None = Field(
        default=None,
        description="""Compiler version string""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": ["PythonInfo", "OSInfo", "CompilerInfo"],
            }
        },
    )
    path: str | None = Field(
        default=None,
        description="""Absolute path to compiler binary""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["PythonInfo", "CompilerInfo"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about this compiler""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "EnvironmentArtifact",
                    "PythonInfo",
                    "OSInfo",
                    "CompilerInfo",
                    "ModuleSystemInfo",
                ],
            }
        },
    )


class ModuleSystemInfo(ConfiguredBaseModel):
    """
    Environment module system information
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/environment"}
    )

    available: bool = Field(
        default=...,
        description="""Whether a module system is available""",
        json_schema_extra={
            "linkml_meta": {"alias": "available", "domain_of": ["ModuleSystemInfo"]}
        },
    )
    type: str | None = Field(
        default=None,
        description="""Module system type (lmod, environment-modules, none)""",
        json_schema_extra={
            "linkml_meta": {"alias": "type", "domain_of": ["ModuleSystemInfo"]}
        },
    )
    loaded_modules: list[str] | None = Field(
        default=None,
        description="""Currently loaded modules""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "loaded_modules",
                "domain_of": ["ModuleSystemInfo"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about module system""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "EnvironmentArtifact",
                    "PythonInfo",
                    "OSInfo",
                    "CompilerInfo",
                    "ModuleSystemInfo",
                ],
            }
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
EnvironmentArtifact.model_rebuild()
PythonInfo.model_rebuild()
OSInfo.model_rebuild()
CompilerInfo.model_rebuild()
ModuleSystemInfo.model_rebuild()
