"""
Discovery Engine Pydantic Models - Filesystem.

AUTO-GENERATED from imas_codex/ontology/discovery/filesystem.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-discovery-models --force
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "discovery",
        "default_range": "string",
        "description": "Schema for filesystem exploration artifacts. Captures "
        "directory structure, file organization, and important paths.",
        "id": "https://iter.org/imas-codex/discovery/filesystem",
        "imports": ["linkml:types"],
        "name": "discovery_filesystem",
        "prefixes": {
            "discovery": {
                "prefix_prefix": "discovery",
                "prefix_reference": "https://iter.org/imas-codex/discovery/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex/imas_codex/ontology/discovery/filesystem.yaml",
        "title": "Filesystem Discovery Schema",
    }
)


class NodeType(str, Enum):
    """
    Types of filesystem nodes
    """

    file = "file"
    """
    Regular file
    """
    directory = "directory"
    """
    Directory
    """
    symlink = "symlink"
    """
    Symbolic link
    """
    other = "other"
    """
    Other node types (sockets, devices, etc.)
    """


class PathType(str, Enum):
    """
    Categories of important paths
    """

    data = "data"
    """
    Data storage paths
    """
    code = "code"
    """
    Source code and scripts
    """
    docs = "docs"
    """
    Documentation and wikis
    """
    config = "config"
    """
    Configuration files
    """
    output = "output"
    """
    Output and results
    """
    scratch = "scratch"
    """
    Temporary or scratch space
    """


class FilesystemArtifact(ConfiguredBaseModel):
    """
    Filesystem exploration results. Contains discovered paths, directory structure, and organization patterns. Supports partial updates for incremental discovery.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/filesystem"}
    )

    facility: str = Field(
        default=...,
        description="""Facility identifier (e.g., epfl, jet, iter)""",
        json_schema_extra={
            "linkml_meta": {"alias": "facility", "domain_of": ["FilesystemArtifact"]}
        },
    )
    explored_at: datetime = Field(
        default=...,
        description="""Timestamp when this artifact was created""",
        json_schema_extra={
            "linkml_meta": {"alias": "explored_at", "domain_of": ["FilesystemArtifact"]}
        },
    )
    root_paths: list[str] | None = Field(
        default=None,
        description="""Root paths that were explored""",
        json_schema_extra={
            "linkml_meta": {"alias": "root_paths", "domain_of": ["FilesystemArtifact"]}
        },
    )
    tree: FilesystemNode | None = Field(
        default=None,
        description="""Root filesystem node (tree structure)""",
        json_schema_extra={
            "linkml_meta": {"alias": "tree", "domain_of": ["FilesystemArtifact"]}
        },
    )
    statistics: ScanStatistics | None = Field(
        default=None,
        description="""Exploration statistics""",
        json_schema_extra={
            "linkml_meta": {"alias": "statistics", "domain_of": ["FilesystemArtifact"]}
        },
    )
    important_paths: list[ImportantPath] | None = Field(
        default=None,
        description="""Notable paths discovered during exploration""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "important_paths",
                "domain_of": ["FilesystemArtifact"],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Freeform observations about filesystem organization""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": ["FilesystemArtifact", "FilesystemNode", "ImportantPath"],
            }
        },
    )


class FilesystemNode(ConfiguredBaseModel):
    """
    A node in the filesystem tree. Can represent files, directories, or symlinks. Forms a recursive tree structure.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/filesystem"}
    )

    path: str = Field(
        default=...,
        description="""Absolute path to this node""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["FilesystemNode", "ImportantPath"],
            }
        },
    )
    name: str | None = Field(
        default=None,
        description="""Basename of the path""",
        json_schema_extra={
            "linkml_meta": {"alias": "name", "domain_of": ["FilesystemNode"]}
        },
    )
    node_type: NodeType = Field(
        default=...,
        description="""Type of filesystem node""",
        json_schema_extra={
            "linkml_meta": {"alias": "node_type", "domain_of": ["FilesystemNode"]}
        },
    )
    size: int | None = Field(
        default=None,
        description="""Size in bytes (for files)""",
        json_schema_extra={
            "linkml_meta": {"alias": "size", "domain_of": ["FilesystemNode"]}
        },
    )
    modified: datetime | None = Field(
        default=None,
        description="""Last modification timestamp""",
        json_schema_extra={
            "linkml_meta": {"alias": "modified", "domain_of": ["FilesystemNode"]}
        },
    )
    permissions: str | None = Field(
        default=None,
        description="""Unix permission string (e.g., rwxr-xr-x)""",
        json_schema_extra={
            "linkml_meta": {"alias": "permissions", "domain_of": ["FilesystemNode"]}
        },
    )
    children: list[FilesystemNode] | None = Field(
        default=None,
        description="""Child nodes (for directories)""",
        json_schema_extra={
            "linkml_meta": {"alias": "children", "domain_of": ["FilesystemNode"]}
        },
    )
    symlink_target: str | None = Field(
        default=None,
        description="""Target path for symlinks""",
        json_schema_extra={
            "linkml_meta": {"alias": "symlink_target", "domain_of": ["FilesystemNode"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about this node""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": ["FilesystemArtifact", "FilesystemNode", "ImportantPath"],
            }
        },
    )


class ScanStatistics(ConfiguredBaseModel):
    """
    Statistics about a filesystem exploration
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/filesystem"}
    )

    total_files: int | None = Field(
        default=None,
        description="""Total number of files discovered""",
        json_schema_extra={
            "linkml_meta": {"alias": "total_files", "domain_of": ["ScanStatistics"]}
        },
    )
    total_directories: int | None = Field(
        default=None,
        description="""Total number of directories discovered""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "total_directories",
                "domain_of": ["ScanStatistics"],
            }
        },
    )
    total_symlinks: int | None = Field(
        default=None,
        description="""Total number of symlinks discovered""",
        json_schema_extra={
            "linkml_meta": {"alias": "total_symlinks", "domain_of": ["ScanStatistics"]}
        },
    )
    total_size_bytes: int | None = Field(
        default=None,
        description="""Total size of all files in bytes""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "total_size_bytes",
                "domain_of": ["ScanStatistics"],
            }
        },
    )
    scan_duration_seconds: float | None = Field(
        default=None,
        description="""How long the exploration took""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "scan_duration_seconds",
                "domain_of": ["ScanStatistics"],
            }
        },
    )
    excluded_paths: int | None = Field(
        default=None,
        description="""Number of paths excluded by filters""",
        json_schema_extra={
            "linkml_meta": {"alias": "excluded_paths", "domain_of": ["ScanStatistics"]}
        },
    )


class ImportantPath(ConfiguredBaseModel):
    """
    A notable path with description of its purpose
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/filesystem"}
    )

    path: str = Field(
        default=...,
        description="""Absolute path""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["FilesystemNode", "ImportantPath"],
            }
        },
    )
    purpose: str = Field(
        default=...,
        description="""What this path contains or is used for""",
        json_schema_extra={
            "linkml_meta": {"alias": "purpose", "domain_of": ["ImportantPath"]}
        },
    )
    path_type: PathType | None = Field(
        default=None,
        description="""Type of path (data, code, docs, config)""",
        json_schema_extra={
            "linkml_meta": {"alias": "path_type", "domain_of": ["ImportantPath"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Additional observations about this path""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": ["FilesystemArtifact", "FilesystemNode", "ImportantPath"],
            }
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
FilesystemArtifact.model_rebuild()
FilesystemNode.model_rebuild()
ScanStatistics.model_rebuild()
ImportantPath.model_rebuild()
