"""
Discovery Engine Pydantic Models - Tools.

AUTO-GENERATED from imas_codex/ontology/discovery/tools.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-discovery-models --force
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "discovery",
        "default_range": "string",
        "description": "Schema for tools exploration artifacts. Captures availability "
        "and versions of command-line tools on the remote facility.",
        "id": "https://iter.org/imas-codex/discovery/tools",
        "imports": ["linkml:types"],
        "name": "discovery_tools",
        "prefixes": {
            "discovery": {
                "prefix_prefix": "discovery",
                "prefix_reference": "https://iter.org/imas-codex/discovery/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex/imas_codex/ontology/discovery/tools.yaml",
        "title": "Tools Discovery Schema",
    }
)


class ToolCategory(str, Enum):
    """
    Categories of CLI tools
    """

    search = "search"
    """
    Search tools (rg, ag, grep, find)
    """
    text = "text"
    """
    Text processing (awk, sed, jq)
    """
    file = "file"
    """
    File utilities (tree, file, stat, ls)
    """
    editor = "editor"
    """
    Text editors (vim, nano, emacs)
    """
    vcs = "vcs"
    """
    Version control (git, svn, hg)
    """
    network = "network"
    """
    Network tools (wget, curl, rsync, ssh)
    """
    build = "build"
    """
    Build tools (make, cmake, ninja)
    """
    compiler = "compiler"
    """
    Compilers (gcc, gfortran, icc, icx)
    """
    mpi = "mpi"
    """
    MPI tools (mpirun, mpicc, srun)
    """
    scheduler = "scheduler"
    """
    Job schedulers (sbatch, qsub, bsub)
    """
    data = "data"
    """
    Data tools (h5dump, ncdump, mdstcl)
    """
    python = "python"
    """
    Python tools (pip, conda, jupyter)
    """
    other = "other"
    """
    Other/uncategorized tools
    """


class ToolsArtifact(ConfiguredBaseModel):
    """
    Collection of available CLI tools on the remote facility. Supports partial updates - tools can be added incrementally.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/tools"}
    )

    facility: str = Field(
        default=...,
        description="""Facility identifier (e.g., epfl, jet, iter)""",
        json_schema_extra={
            "linkml_meta": {"alias": "facility", "domain_of": ["ToolsArtifact"]}
        },
    )
    explored_at: datetime = Field(
        default=...,
        description="""Timestamp when this artifact was created""",
        json_schema_extra={
            "linkml_meta": {"alias": "explored_at", "domain_of": ["ToolsArtifact"]}
        },
    )
    tools: list[ToolInfo] | None = Field(
        default=None,
        description="""List of discovered tools""",
        json_schema_extra={
            "linkml_meta": {"alias": "tools", "domain_of": ["ToolsArtifact"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Freeform observations about tool availability""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": ["ToolsArtifact", "ToolInfo"],
            }
        },
    )


class ToolInfo(ConfiguredBaseModel):
    """
    Information about a single CLI tool
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://iter.org/imas-codex/discovery/tools"}
    )

    name: str = Field(
        default=...,
        description="""Tool name (e.g., rg, grep, h5dump)""",
        json_schema_extra={"linkml_meta": {"alias": "name", "domain_of": ["ToolInfo"]}},
    )
    available: bool = Field(
        default=...,
        description="""Whether the tool is available and executable""",
        json_schema_extra={
            "linkml_meta": {"alias": "available", "domain_of": ["ToolInfo"]}
        },
    )
    path: str | None = Field(
        default=None,
        description="""Absolute path to the tool binary (if available)""",
        json_schema_extra={"linkml_meta": {"alias": "path", "domain_of": ["ToolInfo"]}},
    )
    version: str | None = Field(
        default=None,
        description="""Tool version string (if available)""",
        json_schema_extra={
            "linkml_meta": {"alias": "version", "domain_of": ["ToolInfo"]}
        },
    )
    category: ToolCategory | None = Field(
        default=None,
        description="""Tool category for organization""",
        json_schema_extra={
            "linkml_meta": {"alias": "category", "domain_of": ["ToolInfo"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Observations about this tool""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": ["ToolsArtifact", "ToolInfo"],
            }
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
ToolsArtifact.model_rebuild()
ToolInfo.model_rebuild()
