"""Tests for grammar-segment filters in _search_standard_names (W40 Phase 5).

Verifies that when physical_base / subject / transformation / … kwargs are
provided, the search routes to the segment-filter Cypher path using typed
graph edges (HAS_PHYSICAL_BASE, HAS_SUBJECT, …).

All tests are mock-based — no live Neo4j required.
"""

from __future__ import annotations

from unittest.mock import MagicMock, call, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------


def _make_gc(return_value=None):
    """Create a mock GraphClient."""
    gc = MagicMock()
    gc.query = MagicMock(return_value=return_value or [])
    return gc


def _sn_row(name: str = "electron_temperature") -> dict:
    """Minimal StandardName row dict."""
    return {
        "name": name,
        "description": f"Description of {name}",
        "kind": "scalar",
        "unit": "eV",
        "pipeline_status": "drafted",
        "documentation": "",
        "cocos_transformation_type": "",
        "cocos": None,
        "score": 1.0,
    }


# ---------------------------------------------------------------------------
# Test: segment filter routes to _segment_filter_search_standard_names
# ---------------------------------------------------------------------------


class TestSegmentFilterRouting:
    """When any segment filter kwarg is set, the search must use
    _segment_filter_search_standard_names, not the vector/keyword path."""

    def test_physical_base_filter_calls_segment_search(self) -> None:
        """physical_base kwarg must route to _segment_filter_search_standard_names."""
        gc = _make_gc(return_value=[_sn_row("electron_temperature")])

        with (
            patch(
                "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
                return_value=[_sn_row("electron_temperature")],
            ) as mock_seg,
            patch("imas_codex.llm.sn_tools._vector_search_standard_names") as mock_vec,
            patch("imas_codex.llm.sn_tools._keyword_search_standard_names") as mock_kw,
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        mock_seg.assert_called_once()
        mock_vec.assert_not_called()
        mock_kw.assert_not_called()
        assert "electron_temperature" in result

    def test_subject_filter_calls_segment_search(self) -> None:
        """subject kwarg must route to _segment_filter_search_standard_names."""
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
            return_value=[],
        ) as mock_seg:
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names("electron", subject="electron", gc=gc)

        mock_seg.assert_called_once()

    def test_no_filter_uses_keyword_fallback(self) -> None:
        """With no segment filters and no embedding, keyword search is used."""
        gc = _make_gc(return_value=[])

        with (
            patch(
                "imas_codex.llm.sn_tools._keyword_search_standard_names",
                return_value=[],
            ) as mock_kw,
            patch(
                "imas_codex.llm.sn_tools._segment_filter_search_standard_names"
            ) as mock_seg,
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names("temperature", gc=gc)

        mock_kw.assert_called_once()
        mock_seg.assert_not_called()


# ---------------------------------------------------------------------------
# Test: _segment_filter_search_standard_names builds correct Cypher
# ---------------------------------------------------------------------------


class TestSegmentFilterCypher:
    """Verify the Cypher generated by _segment_filter_search_standard_names."""

    def test_single_filter_cypher_contains_edge_label(self) -> None:
        """physical_base filter → Cypher must reference HAS_PHYSICAL_BASE."""
        gc = _make_gc()
        from imas_codex.llm.sn_tools import _segment_filter_search_standard_names

        _segment_filter_search_standard_names(
            gc, "temperature", 20, {"physical_base": "temperature"}
        )

        assert gc.query.called
        cypher = gc.query.call_args[0][0]
        assert "HAS_PHYSICAL_BASE" in cypher

    def test_two_filter_cypher_contains_both_labels(self) -> None:
        """physical_base + subject → both edge labels in Cypher."""
        gc = _make_gc()
        from imas_codex.llm.sn_tools import _segment_filter_search_standard_names

        _segment_filter_search_standard_names(
            gc,
            "electron temperature",
            20,
            {"physical_base": "temperature", "subject": "electron"},
        )

        cypher = gc.query.call_args[0][0]
        assert "HAS_PHYSICAL_BASE" in cypher
        assert "HAS_SUBJECT" in cypher

    def test_filter_param_value_passed_to_query(self) -> None:
        """Token value must be passed as a Cypher parameter, not inlined."""
        gc = _make_gc()
        from imas_codex.llm.sn_tools import _segment_filter_search_standard_names

        _segment_filter_search_standard_names(
            gc, "temperature", 10, {"physical_base": "temperature"}
        )

        kwargs = gc.query.call_args[1]
        # One of the kwargs should be the token value
        assert "temperature" in kwargs.values()

    def test_unknown_segment_skipped_gracefully(self) -> None:
        """An unrecognised segment key must not raise and not appear in Cypher."""
        gc = _make_gc()
        from imas_codex.llm.sn_tools import _segment_filter_search_standard_names

        # Should not raise
        _segment_filter_search_standard_names(
            gc, "anything", 5, {"not_a_real_segment": "foo"}
        )

        assert gc.query.called
        cypher = gc.query.call_args[0][0]
        # Only StandardName match should be present
        assert "MATCH (sn:StandardName)" in cypher

    def test_k_limit_passed_to_query(self) -> None:
        """k parameter must be forwarded as the LIMIT value."""
        gc = _make_gc()
        from imas_codex.llm.sn_tools import _segment_filter_search_standard_names

        _segment_filter_search_standard_names(gc, "x", 7, {"subject": "electron"})

        kwargs = gc.query.call_args[1]
        assert kwargs.get("k") == 7


# ---------------------------------------------------------------------------
# Test: end-to-end single-filter — single segment filter returns only matches
# ---------------------------------------------------------------------------


class TestSegmentFilterEndToEnd:
    """Integration-style tests over _search_standard_names with mock graph."""

    def test_single_segment_filter_returns_matching_rows(self) -> None:
        """physical_base='temperature' should return temperature-based names only."""
        matching_row = _sn_row("electron_temperature")
        gc = _make_gc()

        with patch(
            "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
            return_value=[matching_row],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        assert "electron_temperature" in result
        assert "plasma_current" not in result

    def test_two_segment_and_filter(self) -> None:
        """physical_base + subject must both appear in the segment_filters dict."""
        gc = _make_gc(return_value=[])

        captured: list[dict] = []

        def fake_segment_search(gc_, query, k, segment_filters):
            captured.append(segment_filters)
            return []

        with patch(
            "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
            side_effect=fake_segment_search,
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names(
                "electron temperature",
                physical_base="temperature",
                subject="electron",
                gc=gc,
            )

        assert len(captured) == 1
        filters = captured[0]
        assert filters.get("physical_base") == "temperature"
        assert filters.get("subject") == "electron"

    def test_no_match_returns_empty_report(self) -> None:
        """When graph returns no rows, result must indicate no matches found."""
        gc = _make_gc()

        with patch(
            "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
            return_value=[],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "nothing", physical_base="nonexistent_token", gc=gc
            )

        assert "No standard names found" in result

    def test_fallback_when_no_typed_edges_in_graph(self) -> None:
        """When graph has no typed edges, segment filter returns empty — no error."""
        # Graph query returns nothing (typed edges not yet migrated)
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._segment_filter_search_standard_names",
            return_value=[],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        # Must not raise; must return a well-formed "no results" report
        assert isinstance(result, str)
        assert "No standard names found" in result


# ---------------------------------------------------------------------------
# Test: MCP server schema exposes segment filter params
# ---------------------------------------------------------------------------


class TestMCPServerSegmentParams:
    """Verify search_standard_names tool in server.py accepts segment params."""

    def test_search_sn_tool_accepts_physical_base(self) -> None:
        """search_standard_names tool must accept physical_base and other segment kwargs."""
        import inspect

        from imas_codex.llm.server import AgentsServer

        server = AgentsServer(dd_only=False, include_standard_names=True)

        # Find the registered search_standard_names tool function via MCP components
        tool_fn = None
        for key, component in server.mcp._local_provider._components.items():
            if key.startswith("tool:") and "search_standard_names" in key:
                tool_fn = component.fn
                break

        assert tool_fn is not None, "search_standard_names tool not registered"
        sig = inspect.signature(tool_fn)
        params = sig.parameters
        assert "physical_base" in params, "physical_base param must be in MCP tool"
        assert "subject" in params, "subject param must be in MCP tool"
        assert "transformation" in params, "transformation param must be in MCP tool"
        assert "component" in params, "component param must be in MCP tool"
        assert "coordinate" in params, "coordinate param must be in MCP tool"
        assert "process" in params, "process param must be in MCP tool"
        assert "position" in params, "position param must be in MCP tool"
        assert "region" in params, "region param must be in MCP tool"
        assert "device" in params, "device param must be in MCP tool"
        assert "geometric_base" in params, "geometric_base param must be in MCP tool"
