"""
Facility Configuration Pydantic Models.

AUTO-GENERATED from imas_codex/schemas/facility_config.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-models --force

Usage:
    from imas_codex.config.models import FacilityConfig
    config = FacilityConfig.model_validate(yaml_data)
"""

from __future__ import annotations 

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal 
from enum import Enum 
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    field_validator
)


metamodel_version = "None"
version = "0.4.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment = True,
        validate_default = True,
        extra = "ignore",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )
    pass




class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta({'default_prefix': 'fc',
     'default_range': 'string',
     'description': 'Schema for per-facility YAML configuration files. Defines '
                    'required and optional fields for both public and private '
                    'config sections. Agents should edit these files via MCP tools '
                    '(update_facility_infrastructure, add_exploration_note) which '
                    'enforce this schema.',
     'id': 'https://imas.iter.org/schemas/facility_config',
     'imports': ['linkml:types'],
     'license': 'MIT',
     'name': 'facility_config',
     'prefixes': {'fc': {'prefix_prefix': 'fc',
                         'prefix_reference': 'https://imas.iter.org/schemas/facility_config/'},
                  'linkml': {'prefix_prefix': 'linkml',
                             'prefix_reference': 'https://w3id.org/linkml/'}},
     'source_file': '/home/mcintos/Code/imas-codex/imas_codex/schemas/facility_config.yaml',
     'title': 'Facility Configuration Schema'} )

class DataSystemType(str, Enum):
    """
    Types of data systems available at facilities
    """
    mdsplus = "mdsplus"
    """
    MDSplus tree-based data system
    """
    tdi = "tdi"
    """
    TDI function-based data access layer
    """
    uda = "uda"
    """
    Universal Data Access (UDA) system
    """
    imas = "imas"
    """
    IMAS native data format
    """
    ppf = "ppf"
    """
    JET Processed Pulse File system
    """
    edas = "edas"
    """
    JT-60SA EDAS data system
    """
    hdf5 = "hdf5"
    """
    HDF5 file-based storage
    """
    netcdf = "netcdf"
    """
    NetCDF scientific data format
    """


class WikiSiteType(str, Enum):
    """
    Types of wiki/documentation sites
    """
    mediawiki = "mediawiki"
    """
    MediaWiki-based sites (Wikipedia, SPCwiki)
    """
    confluence = "confluence"
    """
    Atlassian Confluence
    """
    twiki = "twiki"
    """
    TWiki/Foswiki installation
    """
    twiki_static = "twiki_static"
    """
    TWiki static HTML export
    """
    static = "static"
    """
    Static HTML documentation site
    """
    static_html = "static_html"
    """
    Static HTML site (alias for static)
    """


class WikiAuthType(str, Enum):
    """
    Authentication methods for wiki sites
    """
    none = "none"
    """
    No authentication required
    """
    tequila = "tequila"
    """
    EPFL Tequila SSO
    """
    keycloak = "keycloak"
    """
    Keycloak OIDC (JET)
    """
    basic = "basic"
    """
    HTTP Basic authentication
    """
    session = "session"
    """
    Session-based auth (login form, cookies)
    """
    ssh_proxy = "ssh_proxy"
    """
    Access only via SSH tunnel
    """


class NameFormat(str, Enum):
    """
    Format of user names in GECOS field
    """
    first_last = "first_last"
    """
    First Last format
    """
    last_first = "last_first"
    """
    Last, First format
    """
    username = "username"
    """
    Username only (no real name)
    """



class FacilityConfig(ConfiguredBaseModel):
    """
    Root configuration for a facility. Combines public and private fields. Public fields go in <facility>.yaml, private in <facility>_private.yaml. Validation merges both files before checking required fields.
    Note: The loader renames 'facility' to 'id', so either is accepted.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:FacilityConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config',
         'tree_root': True})

    facility: Optional[str] = Field(default=None, description="""Facility identifier in YAML files (e.g., \"tcv\", \"jet\")""", json_schema_extra = { "linkml_meta": {'alias': 'facility', 'domain_of': ['FacilityConfig']} })
    id: Optional[str] = Field(default=None, description="""Facility identifier after loading (alias of facility)""", json_schema_extra = { "linkml_meta": {'alias': 'id', 'domain_of': ['FacilityConfig']} })
    name: str = Field(default=..., description="""Human-readable facility name""", json_schema_extra = { "linkml_meta": {'alias': 'name', 'domain_of': ['FacilityConfig']} })
    machine: str = Field(default=..., description="""Tokamak/stellarator machine name""", json_schema_extra = { "linkml_meta": {'alias': 'machine', 'domain_of': ['FacilityConfig']} })
    description: Optional[str] = Field(default=None, description="""Brief facility description""", json_schema_extra = { "linkml_meta": {'alias': 'description',
         'domain_of': ['FacilityConfig', 'DiscoveryRootConfig', 'WikiSiteConfig']} })
    location: Optional[str] = Field(default=None, description="""Geographic location""", json_schema_extra = { "linkml_meta": {'alias': 'location', 'domain_of': ['FacilityConfig']} })
    ssh_host: Optional[str] = Field(default=None, description="""SSH host alias for connection (configured in ~/.ssh/config)""", json_schema_extra = { "linkml_meta": {'alias': 'ssh_host', 'domain_of': ['FacilityConfig']} })
    data_systems: Optional[list | dict] = Field(default=None, description="""Data systems available. Can be list of strings [\"mdsplus\", \"uda\"] or dict with details {mdsplus: {available: true, ...}}.""", json_schema_extra = { "linkml_meta": {'alias': 'data_systems', 'domain_of': ['FacilityConfig']} })
    discovery_roots: Optional[list] = Field(default=None, description="""Root paths for discovery pipeline seeding. Can be simple strings [\"/home\", \"/work\"] or structured [{path: \"/home\", category: \"container\"}].""", json_schema_extra = { "linkml_meta": {'alias': 'discovery_roots', 'domain_of': ['FacilityConfig']} })
    data_sources: Optional[DataSourcesConfig] = Field(default=None, description="""Data source configuration for signal discovery""", json_schema_extra = { "linkml_meta": {'alias': 'data_sources', 'domain_of': ['FacilityConfig']} })
    data_access_patterns: Optional[DataAccessPatternsConfig] = Field(default=None, description="""Data access patterns discovered during initial facility exploration. Populated by exploration agents before signal discovery runs. Describes how data is organized, what tools/APIs exist, what naming conventions are used. This informs downstream tools (wiki scoring, signal extraction, code ingestion) about what to look for at this facility.""", json_schema_extra = { "linkml_meta": {'alias': 'data_access_patterns', 'domain_of': ['FacilityConfig']} })
    wiki_sites: Optional[list[WikiSiteConfig]] = Field(default=None, description="""Wiki/documentation sites""", json_schema_extra = { "linkml_meta": {'alias': 'wiki_sites', 'domain_of': ['FacilityConfig']} })
    user_info: Optional[UserInfoConfig] = Field(default=None, description="""User info discovery configuration""", json_schema_extra = { "linkml_meta": {'alias': 'user_info', 'domain_of': ['FacilityConfig']} })
    hostnames: Optional[list[str]] = Field(default=None, description="""Network hostnames for this facility""", json_schema_extra = { "linkml_meta": {'alias': 'hostnames',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    nfs_mounts: Optional[list] = Field(default=None, description="""NFS mount points (list of {source, target, options})""", json_schema_extra = { "linkml_meta": {'alias': 'nfs_mounts',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    paths: Optional[dict] = Field(default=None, description="""Key filesystem paths (nested dict structure)""", json_schema_extra = { "linkml_meta": {'alias': 'paths',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig', 'HDF5Config']} })
    svn: Optional[dict] = Field(default=None, description="""SVN repository URLs""", json_schema_extra = { "linkml_meta": {'alias': 'svn',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    excludes: Optional[dict] = Field(default=None, description="""Paths/patterns to exclude during exploration""", json_schema_extra = { "linkml_meta": {'alias': 'excludes',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    tools: Optional[dict] = Field(default=None, description="""Tool availability map (tool -> version)""", json_schema_extra = { "linkml_meta": {'alias': 'tools',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    os_info: Optional[dict] = Field(default=None, description="""Operating system details""", json_schema_extra = { "linkml_meta": {'alias': 'os_info',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    python_info: Optional[dict] = Field(default=None, description="""Python environment details""", json_schema_extra = { "linkml_meta": {'alias': 'python_info',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    compilers: Optional[dict] = Field(default=None, description="""Compiler availability""", json_schema_extra = { "linkml_meta": {'alias': 'compilers',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    containers: Optional[dict] = Field(default=None, description="""Available container images""", json_schema_extra = { "linkml_meta": {'alias': 'containers',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })
    exploration_notes: Optional[list[str]] = Field(default=None, description="""Free-form exploration notes (timestamped)""", json_schema_extra = { "linkml_meta": {'alias': 'exploration_notes',
         'annotations': {'is_private': {'tag': 'is_private', 'value': True}},
         'domain_of': ['FacilityConfig']} })


class DiscoveryRootConfig(ConfiguredBaseModel):
    """
    Structured configuration for a discovery root path. Used in private configs to provide category and priority hints for discovery seeding. Public configs may use simple string paths instead.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:DiscoveryRootConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    path: str = Field(default=..., description="""Absolute filesystem path to seed""", json_schema_extra = { "linkml_meta": {'alias': 'path', 'domain_of': ['DiscoveryRootConfig']} })
    category: Optional[str] = Field(default=None, description="""Discovery category for balanced seeding. Values: container, modeling_code, analysis_code, data_access, workflow, experimental_data, documentation.""", json_schema_extra = { "linkml_meta": {'alias': 'category', 'domain_of': ['DiscoveryRootConfig']} })
    description: Optional[str] = Field(default=None, description="""Brief description of what this root contains""", json_schema_extra = { "linkml_meta": {'alias': 'description',
         'domain_of': ['FacilityConfig', 'DiscoveryRootConfig', 'WikiSiteConfig']} })
    priority: Optional[str] = Field(default=None, description="""Seeding priority (high, medium, low)""", json_schema_extra = { "linkml_meta": {'alias': 'priority', 'domain_of': ['DiscoveryRootConfig']} })
    expand_depth: Optional[int] = Field(default=None, description="""Maximum depth to expand from this root""", json_schema_extra = { "linkml_meta": {'alias': 'expand_depth', 'domain_of': ['DiscoveryRootConfig']} })


class WikiSiteConfig(ConfiguredBaseModel):
    """
    Configuration for a wiki/documentation site. Used by wiki discovery to enumerate pages and artifacts.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:WikiSiteConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    url: str = Field(default=..., description="""Base URL of the wiki site""", json_schema_extra = { "linkml_meta": {'alias': 'url', 'domain_of': ['WikiSiteConfig']} })
    portal_page: Optional[str] = Field(default="Main_Page", description="""Main portal/landing page name (e.g., \"Main_Page\", \"Portal:TCV\")""", json_schema_extra = { "linkml_meta": {'alias': 'portal_page',
         'domain_of': ['WikiSiteConfig'],
         'ifabsent': 'Main_Page'} })
    description: Optional[str] = Field(default=None, description="""Brief description of the wiki content""", json_schema_extra = { "linkml_meta": {'alias': 'description',
         'domain_of': ['FacilityConfig', 'DiscoveryRootConfig', 'WikiSiteConfig']} })
    site_type: Optional[WikiSiteType] = Field(default='mediawiki', description="""Type of wiki software""", json_schema_extra = { "linkml_meta": {'alias': 'site_type', 'domain_of': ['WikiSiteConfig'], 'ifabsent': 'mediawiki'} })
    access_method: Optional[str] = Field(default="direct", description="""How the site is accessed (direct, ssh_tunnel)""", json_schema_extra = { "linkml_meta": {'alias': 'access_method',
         'domain_of': ['WikiSiteConfig'],
         'ifabsent': 'direct'} })
    auth_type: Optional[WikiAuthType] = Field(default='none', description="""Authentication method""", json_schema_extra = { "linkml_meta": {'alias': 'auth_type', 'domain_of': ['WikiSiteConfig'], 'ifabsent': 'none'} })
    credential_service: Optional[str] = Field(default=None, description="""Keyring service name for credentials""", json_schema_extra = { "linkml_meta": {'alias': 'credential_service', 'domain_of': ['WikiSiteConfig']} })
    ssh_available: Optional[bool] = Field(default=None, description="""Whether SSH tunnel is available as fallback""", json_schema_extra = { "linkml_meta": {'alias': 'ssh_available', 'domain_of': ['WikiSiteConfig']} })


class DataSourcesConfig(ConfiguredBaseModel):
    """
    Data source configuration for signal discovery. Specifies how to enumerate signals from each data system. Each key maps to a scanner plugin that knows how to extract signals from that data source type.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:DataSourcesConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    tdi: Optional[TDIConfig] = Field(default=None, description="""TDI function configuration (MDSplus TDI expression files)""", json_schema_extra = { "linkml_meta": {'alias': 'tdi', 'domain_of': ['DataSourcesConfig']} })
    mdsplus: Optional[MDSplusConfig] = Field(default=None, description="""MDSplus tree configuration (direct tree traversal)""", json_schema_extra = { "linkml_meta": {'alias': 'mdsplus', 'domain_of': ['DataSourcesConfig']} })
    ppf: Optional[PPFConfig] = Field(default=None, description="""JET PPF configuration (Processed Pulse Files)""", json_schema_extra = { "linkml_meta": {'alias': 'ppf', 'domain_of': ['DataSourcesConfig']} })
    edas: Optional[EDASConfig] = Field(default=None, description="""JT-60SA EDAS configuration (Experiment Data Access System)""", json_schema_extra = { "linkml_meta": {'alias': 'edas', 'domain_of': ['DataSourcesConfig']} })
    hdf5: Optional[HDF5Config] = Field(default=None, description="""HDF5 file configuration""", json_schema_extra = { "linkml_meta": {'alias': 'hdf5', 'domain_of': ['DataSourcesConfig']} })
    imas: Optional[IMASConfig] = Field(default=None, description="""IMAS native data configuration""", json_schema_extra = { "linkml_meta": {'alias': 'imas', 'domain_of': ['DataSourcesConfig']} })


class TDIConfig(ConfiguredBaseModel):
    """
    TDI function data source configuration. TDI (.fun) files provide physics-level accessor functions over raw MDSplus tree paths. Facility-specific (e.g., TCV tcv_eq, tcv_get, tcv_ip).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:TDIConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    primary_path: Optional[str] = Field(default=None, description="""Primary TDI directory path (e.g., /usr/local/CRPP/tdi/tcv)""", json_schema_extra = { "linkml_meta": {'alias': 'primary_path', 'domain_of': ['TDIConfig']} })
    additional_paths: Optional[list[str]] = Field(default=None, description="""Additional TDI directories to scan""", json_schema_extra = { "linkml_meta": {'alias': 'additional_paths', 'domain_of': ['TDIConfig']} })
    reference_shot: Optional[int] = Field(default=None, description="""Reference shot for TDI accessor validation""", json_schema_extra = { "linkml_meta": {'alias': 'reference_shot',
         'domain_of': ['TDIConfig', 'MDSplusConfig', 'EDASConfig', 'IMASConfig']} })
    exclude_functions: Optional[list[str]] = Field(default=None, description="""TDI function names to exclude from signal discovery (case-insensitive). Hardware control, acquisition triggers, and operational dispatch functions that don't return physics data. These functions may load missing shared libraries, print debug output, or perform side effects when executed.""", json_schema_extra = { "linkml_meta": {'alias': 'exclude_functions', 'domain_of': ['TDIConfig']} })


class MDSplusConfig(ConfiguredBaseModel):
    """
    MDSplus data source configuration
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:MDSplusConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    connection_tree: Optional[str] = Field(default=None, description="""Default tree for TDI context""", json_schema_extra = { "linkml_meta": {'alias': 'connection_tree', 'domain_of': ['MDSplusConfig']} })
    trees: Optional[list[str]] = Field(default=None, description="""MDSplus tree names to scan""", json_schema_extra = { "linkml_meta": {'alias': 'trees', 'domain_of': ['MDSplusConfig']} })
    reference_shot: Optional[int] = Field(default=None, description="""Shot number for tree introspection""", json_schema_extra = { "linkml_meta": {'alias': 'reference_shot',
         'domain_of': ['TDIConfig', 'MDSplusConfig', 'EDASConfig', 'IMASConfig']} })


class PPFConfig(ConfiguredBaseModel):
    """
    JET PPF (Processed Pulse File) data source configuration. PPF is organized as Owner/DDA/Dtype entries. Access via SAL REST API, MATLAB ppfget, IDL ppfget, or getdat CLI.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:PPFConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    sal_endpoint: Optional[str] = Field(default=None, description="""SAL REST API endpoint URL""", json_schema_extra = { "linkml_meta": {'alias': 'sal_endpoint', 'domain_of': ['PPFConfig']} })
    reference_pulse: Optional[int] = Field(default=None, description="""Reference pulse for signal validation""", json_schema_extra = { "linkml_meta": {'alias': 'reference_pulse', 'domain_of': ['PPFConfig']} })
    default_owner: Optional[str] = Field(default=None, description="""Default PPF data owner (e.g., \"jetppf\")""", json_schema_extra = { "linkml_meta": {'alias': 'default_owner', 'domain_of': ['PPFConfig']} })
    exclude_ddas: Optional[list[str]] = Field(default=None, description="""DDA identifiers to exclude from discovery""", json_schema_extra = { "linkml_meta": {'alias': 'exclude_ddas', 'domain_of': ['PPFConfig']} })


class EDASConfig(ConfiguredBaseModel):
    """
    JT-60SA EDAS (Experiment Data Access System) configuration. EDAS wraps proprietary data formats with C/Fortran/Python APIs. Signal definitions are in C header files and Python wrapper code.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:EDASConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    api_path: Optional[str] = Field(default=None, description="""Path to EDAS API source files""", json_schema_extra = { "linkml_meta": {'alias': 'api_path', 'domain_of': ['EDASConfig']} })
    header_path: Optional[str] = Field(default=None, description="""Path to EDAS C header files with signal definitions""", json_schema_extra = { "linkml_meta": {'alias': 'header_path', 'domain_of': ['EDASConfig']} })
    reference_shot: Optional[int] = Field(default=None, description="""Reference shot for signal validation""", json_schema_extra = { "linkml_meta": {'alias': 'reference_shot',
         'domain_of': ['TDIConfig', 'MDSplusConfig', 'EDASConfig', 'IMASConfig']} })


class HDF5Config(ConfiguredBaseModel):
    """
    HDF5 file data source configuration
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:HDF5Config',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    paths: Optional[list[str]] = Field(default=None, description="""HDF5 file/directory paths to scan""", json_schema_extra = { "linkml_meta": {'alias': 'paths', 'domain_of': ['FacilityConfig', 'HDF5Config']} })


class IMASConfig(ConfiguredBaseModel):
    """
    IMAS native data source configuration. Used at facilities with native IMAS backend support (ITER, JET post-migration, JT-60SA).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:IMASConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    backends: Optional[list[str]] = Field(default=None, description="""Available IMAS backends (e.g., mdsplus, hdf5, memory)""", json_schema_extra = { "linkml_meta": {'alias': 'backends', 'domain_of': ['IMASConfig']} })
    db_name: Optional[str] = Field(default=None, description="""IMAS database name""", json_schema_extra = { "linkml_meta": {'alias': 'db_name', 'domain_of': ['IMASConfig']} })
    reference_shot: Optional[int] = Field(default=None, description="""Reference shot for IDS enumeration""", json_schema_extra = { "linkml_meta": {'alias': 'reference_shot',
         'domain_of': ['TDIConfig', 'MDSplusConfig', 'EDASConfig', 'IMASConfig']} })


class UserInfoConfig(ConfiguredBaseModel):
    """
    Configuration for user info discovery. Specifies how to extract user names from system (GECOS field, LDAP, etc.).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:UserInfoConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    name_format: Optional[NameFormat] = Field(default='first_last', description="""Format of user names in GECOS field""", json_schema_extra = { "linkml_meta": {'alias': 'name_format',
         'domain_of': ['UserInfoConfig'],
         'ifabsent': 'first_last'} })
    lookup_tools: Optional[list[str]] = Field(default="[getent, passwd, id]", description="""Ordered list of tools to try for name lookup""", json_schema_extra = { "linkml_meta": {'alias': 'lookup_tools',
         'domain_of': ['UserInfoConfig'],
         'ifabsent': '[getent, passwd, id]'} })


class ExcludesConfig(ConfiguredBaseModel):
    """
    Exclusion patterns for discovery. Prevents scanning of large directories that would hang or produce low-value results.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:ExcludesConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    large_dirs: Optional[list[str]] = Field(default=None, description="""Directories that caused timeouts (absolute paths). Discovery skips these entirely.""", json_schema_extra = { "linkml_meta": {'alias': 'large_dirs', 'domain_of': ['ExcludesConfig']} })
    depth_limits: Optional[str] = Field(default=None, description="""Per-path depth limits (map of path -> max_depth). Limits recursion in specific subtrees.""", json_schema_extra = { "linkml_meta": {'alias': 'depth_limits', 'domain_of': ['ExcludesConfig']} })
    patterns: Optional[list[str]] = Field(default=None, description="""Glob patterns to exclude (e.g., \"**/node_modules\", \"**/.git\"). Applied during directory enumeration.""", json_schema_extra = { "linkml_meta": {'alias': 'patterns', 'domain_of': ['ExcludesConfig']} })


class DataAccessPatternsConfig(ConfiguredBaseModel):
    """
    Data access patterns discovered during initial facility exploration. Populated by exploration agents to inform downstream discovery tools. Describes how shot data is organized, what APIs/tools exist, and what naming conventions are used at this facility. This bridges exploration knowledge to scanning/scoring tools.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'class_uri': 'fc:DataAccessPatternsConfig',
         'from_schema': 'https://imas.iter.org/schemas/facility_config'})

    primary_method: Optional[str] = Field(default=None, description="""The primary data access method at this facility (e.g., \"tdi\" for TCV, \"ppf\" for JET, \"edas\" for JT-60SA, \"imas\" for ITER). Informs which scanner plugin to run first.""", json_schema_extra = { "linkml_meta": {'alias': 'primary_method', 'domain_of': ['DataAccessPatternsConfig']} })
    signal_naming: Optional[str] = Field(default=None, description="""How signals are named at this facility. Free text describing the convention (e.g., \"TDI function dispatch: tcv_eq('quantity')\", \"PPF hierarchy: owner/dda/dtype\", \"EDAS channels: eddb_get(channel)\").""", json_schema_extra = { "linkml_meta": {'alias': 'signal_naming', 'domain_of': ['DataAccessPatternsConfig']} })
    shot_identifier: Optional[str] = Field(default=None, description="""What the facility calls shots (e.g., \"shot\" at TCV, \"pulse\" at JET, \"shot\" at JT-60SA). Used to template data access patterns.""", json_schema_extra = { "linkml_meta": {'alias': 'shot_identifier', 'domain_of': ['DataAccessPatternsConfig']} })
    tree_organization: Optional[str] = Field(default=None, description="""How experimental data is organized (e.g., \"MDSplus trees by subsystem\", \"PPF by diagnostic data area\", \"EDAS database tables\").""", json_schema_extra = { "linkml_meta": {'alias': 'tree_organization', 'domain_of': ['DataAccessPatternsConfig']} })
    key_tools: Optional[list[str]] = Field(default=None, description="""Key data access tools/APIs discovered at the facility. E.g., [\"sal\", \"ppfget\", \"getdat\"] for JET, [\"tdiExecute\", \"tcv_get\", \"gdat\"] for TCV, [\"eddb_get\", \"edgis\", \"eslice\"] for JT-60SA.""", json_schema_extra = { "linkml_meta": {'alias': 'key_tools', 'domain_of': ['DataAccessPatternsConfig']} })
    wiki_signal_patterns: Optional[list[str]] = Field(default=None, description="""Patterns observed in wiki pages that indicate signal documentation. E.g., [\"MDSplus path tables\", \"diagnostic node listings\", \"signal catalogs\"]. Helps wiki discovery score pages with data access content higher.""", json_schema_extra = { "linkml_meta": {'alias': 'wiki_signal_patterns', 'domain_of': ['DataAccessPatternsConfig']} })
    code_import_patterns: Optional[list[str]] = Field(default=None, description="""Import patterns that indicate data access code. E.g., [\"import MDSplus\", \"from jet.data import sal\", \"import eddb\"]. Helps code ingestion identify data access files.""", json_schema_extra = { "linkml_meta": {'alias': 'code_import_patterns', 'domain_of': ['DataAccessPatternsConfig']} })
    notes: Optional[list[str]] = Field(default=None, description="""Free-form notes about data access at this facility""", json_schema_extra = { "linkml_meta": {'alias': 'notes', 'domain_of': ['DataAccessPatternsConfig']} })


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
FacilityConfig.model_rebuild()
DiscoveryRootConfig.model_rebuild()
WikiSiteConfig.model_rebuild()
DataSourcesConfig.model_rebuild()
TDIConfig.model_rebuild()
MDSplusConfig.model_rebuild()
PPFConfig.model_rebuild()
EDASConfig.model_rebuild()
HDF5Config.model_rebuild()
IMASConfig.model_rebuild()
UserInfoConfig.model_rebuild()
ExcludesConfig.model_rebuild()
DataAccessPatternsConfig.model_rebuild()

