#!/usr/bin/env python3
"""Build Pydantic models from LinkML schemas.

Source: imas_codex/schemas/facility.yaml
Output: imas_codex/graph/models.py

To regenerate:
    uv run build-models --force
"""

import logging
import subprocess
import sys
from pathlib import Path

import click


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent


def get_schemas_dir() -> Path:
    """Get the schemas directory containing LinkML schemas."""
    return get_project_root() / "imas_codex" / "schemas"


def get_graph_dir() -> Path:
    """Get the graph module directory."""
    return get_project_root() / "imas_codex" / "graph"


@click.command()
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose logging output")
@click.option("--quiet", "-q", is_flag=True, help="Suppress all logging except errors")
@click.option(
    "--force", "-f", is_flag=True, help="Force rebuild even if files already exist"
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be generated without writing files",
)
def build_models(
    verbose: bool,
    quiet: bool,
    force: bool,
    dry_run: bool,
) -> int:
    """Generate Pydantic models from LinkML facility schema.

    This command uses linkml's gen-pydantic generator to create Python models
    from the schemas/facility.yaml schema. The generated code is written to
    imas_codex/graph/models.py.

    Examples:
        build-models              # Generate models
        build-models -v           # Verbose output
        build-models --dry-run    # Preview without writing
        build-models -f           # Force regeneration
    """
    # Set up logging level
    if quiet:
        log_level = logging.ERROR
    elif verbose:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO

    logging.basicConfig(
        level=log_level, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    logger = logging.getLogger(__name__)

    try:
        schemas_dir = get_schemas_dir()
        graph_dir = get_graph_dir()

        # Ensure graph directory exists
        graph_dir.mkdir(parents=True, exist_ok=True)

        schema_file = schemas_dir / "facility.yaml"
        output_file = graph_dir / "models.py"

        # Validate schema exists
        if not schema_file.exists():
            logger.error(f"Schema file not found: {schema_file}")
            click.echo(f"Error: Schema file not found: {schema_file}", err=True)
            return 1

        # Check if output already exists
        if output_file.exists() and not force:
            # Check if schema is newer than output
            if schema_file.stat().st_mtime <= output_file.stat().st_mtime:
                logger.info(f"Models up to date at {output_file}")
                click.echo(f"Models up to date: {output_file}")
                return 0
            logger.info("Schema newer than models, regenerating...")

        logger.info(f"Generating Pydantic models from {schema_file}")

        if dry_run:
            click.echo(f"Would generate: {output_file}")
            return 0

        # Run gen-pydantic
        cmd = ["gen-pydantic", str(schema_file)]

        logger.debug(f"Running command: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            logger.error(f"gen-pydantic failed: {result.stderr}")
            click.echo(f"Error: gen-pydantic failed:\n{result.stderr}", err=True)
            return 1

        # Add header comment to generated code
        header = '''"""
Facility Knowledge Graph Pydantic Models.

AUTO-GENERATED from imas_codex/schemas/facility.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-models --force
"""

'''
        generated_code = header + result.stdout

        # Write output
        output_file.write_text(generated_code)
        logger.info(f"Generated models written to {output_file}")
        click.echo(f"Generated: {output_file}")

        return 0

    except Exception as e:
        logger.error(f"Error generating models: {e}")
        if verbose:
            logger.exception("Full traceback:")
        click.echo(f"Error: {e}", err=True)
        return 1


if __name__ == "__main__":
    sys.exit(build_models())
