#!/usr/bin/env python3
"""
Build Pydantic models from LinkML discovery schema.

This script generates Python Pydantic models from the LinkML schema definitions
in imas_codex/ontology/. The generated models are written to
imas_codex/discovery/models.py and should NOT be edited directly.
"""

import logging
import subprocess
import sys
from pathlib import Path

import click


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent


def get_ontology_dir() -> Path:
    """Get the ontology directory containing LinkML schemas."""
    return get_project_root() / "imas_codex" / "ontology"


def get_discovery_dir() -> Path:
    """Get the discovery module directory."""
    return get_project_root() / "imas_codex" / "discovery"


@click.command()
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose logging output")
@click.option("--quiet", "-q", is_flag=True, help="Suppress all logging except errors")
@click.option(
    "--force", "-f", is_flag=True, help="Force rebuild even if files already exist"
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be generated without writing files",
)
def build_discovery_models(
    verbose: bool,
    quiet: bool,
    force: bool,
    dry_run: bool,
) -> int:
    """Generate Pydantic models from LinkML discovery schema.

    This command uses linkml's gen-pydantic generator to create Python models
    from the discovery.yaml schema. The generated code is written to
    imas_codex/discovery/models.py.

    Examples:
        build-discovery-models              # Generate models
        build-discovery-models -v           # Verbose output
        build-discovery-models --dry-run    # Preview without writing
        build-discovery-models -f           # Force regeneration
    """
    # Set up logging level
    if quiet:
        log_level = logging.ERROR
    elif verbose:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO

    logging.basicConfig(
        level=log_level, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    logger = logging.getLogger(__name__)

    try:
        ontology_dir = get_ontology_dir()
        discovery_dir = get_discovery_dir()
        schema_file = ontology_dir / "discovery.yaml"
        output_file = discovery_dir / "models.py"

        # Validate schema exists
        if not schema_file.exists():
            logger.error(f"Schema file not found: {schema_file}")
            click.echo(f"Error: Schema file not found: {schema_file}", err=True)
            return 1

        # Check if output already exists
        if output_file.exists() and not force:
            logger.info(f"Models already exist at {output_file}")
            logger.info("Use --force to regenerate")
            click.echo(
                f"Models already exist at {output_file} (use --force to regenerate)"
            )
            return 0

        # Ensure discovery directory exists
        discovery_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Generating Pydantic models from {schema_file}")

        if dry_run:
            click.echo(f"Would generate: {output_file}")
            click.echo(f"From schema: {schema_file}")
            return 0

        # Run gen-pydantic
        cmd = [
            "gen-pydantic",
            "--pydantic-version",
            "2",
            str(schema_file),
        ]

        logger.debug(f"Running command: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            logger.error(f"gen-pydantic failed: {result.stderr}")
            click.echo(f"Error: gen-pydantic failed:\n{result.stderr}", err=True)
            return 1

        # Add header comment to generated code
        header = '''"""
Discovery Engine Pydantic Models.

AUTO-GENERATED from imas_codex/ontology/discovery.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-discovery-models --force
"""

'''
        generated_code = header + result.stdout

        # Write output
        output_file.write_text(generated_code)
        logger.info(f"Generated models written to {output_file}")
        click.echo(f"Generated: {output_file}")

        return 0

    except Exception as e:
        logger.error(f"Error generating models: {e}")
        if verbose:
            logger.exception("Full traceback:")
        click.echo(f"Error: {e}", err=True)
        return 1


if __name__ == "__main__":
    sys.exit(build_discovery_models())
