#!/usr/bin/env python3
"""
Generate PhysicsDomain enum from LinkML schema.

This script reads the LinkML domains.yaml schema and generates a Python
enum compatible with Pydantic (str, Enum). The generated enum replaces
the manually maintained PhysicsDomain in data_model.py.
"""

import sys
from datetime import UTC, datetime
from pathlib import Path

import click
from linkml_runtime.utils.schemaview import SchemaView


def generate_enum_code(schema_path: Path) -> str:
    """Generate Python enum code from LinkML schema.

    Args:
        schema_path: Path to the LinkML YAML schema file.

    Returns:
        Python source code for the enum.
    """
    sv = SchemaView(str(schema_path))
    schema = sv.schema

    # Get the PhysicsDomain enum
    enum_def = sv.get_enum("PhysicsDomain")
    if not enum_def:
        raise ValueError("PhysicsDomain enum not found in schema")

    # Build enum members
    members = []
    for pv_name, pv in enum_def.permissible_values.items():
        # Create enum member name (uppercase with underscores)
        member_name = pv_name.upper()

        # Add member with description as comment
        description = pv.description or ""
        members.append(f'    {member_name} = "{pv_name}"  # {description}')

    # Generate the code
    code = f'''"""
Physics domain enum generated from LinkML schema.

DO NOT EDIT THIS FILE DIRECTLY.
Edit imas_codex/definitions/physics/domains.yaml and run:
    uv run gen-physics-domains

Generated: {datetime.now(UTC).isoformat()}
Schema: {schema.name}
"""

from enum import Enum


class PhysicsDomain(str, Enum):
    """Physics domains for categorizing IMAS Interface Data Structures (IDS).

    Each domain represents a distinct area of fusion plasma physics or
    tokamak engineering. This enum is generated from the LinkML schema
    at definitions/physics/domains.yaml.
    """

{chr(10).join(members)}
'''

    return code


@click.command()
@click.option(
    "--schema",
    type=click.Path(exists=True, path_type=Path),
    default=Path(__file__).parent.parent
    / "imas_codex/definitions/physics/domains.yaml",
    help="Path to LinkML schema file",
)
@click.option(
    "--output",
    type=click.Path(path_type=Path),
    default=None,
    help="Output file path (default: stdout)",
)
@click.option(
    "--check",
    is_flag=True,
    help="Check if generated code matches existing file",
)
def gen_physics_domains(schema: Path, output: Path | None, check: bool) -> int:
    """Generate PhysicsDomain enum from LinkML schema.

    This command reads the domains.yaml LinkML schema and generates a
    Python enum that can be used with Pydantic models.

    Examples:
        gen-physics-domains                    # Print to stdout
        gen-physics-domains --output src/enum.py  # Write to file
        gen-physics-domains --check            # Verify file is up to date
    """
    try:
        code = generate_enum_code(schema)

        if check:
            if not output:
                click.echo("Error: --check requires --output", err=True)
                return 1
            if not output.exists():
                click.echo(f"Error: {output} does not exist", err=True)
                return 1
            existing = output.read_text()
            # Compare ignoring the timestamp line
            existing_lines = [
                line
                for line in existing.splitlines()
                if not line.startswith("Generated:")
            ]
            new_lines = [
                line for line in code.splitlines() if not line.startswith("Generated:")
            ]
            if existing_lines != new_lines:
                click.echo(
                    f"Error: {output} is out of date. Run gen-physics-domains to update.",
                    err=True,
                )
                return 1
            click.echo(f"OK: {output} is up to date")
            return 0

        if output:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(code)
            click.echo(f"Generated {output}")
        else:
            click.echo(code)

        return 0

    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        return 1


if __name__ == "__main__":
    sys.exit(gen_physics_domains())
