"""Tests for SSH worker protocol and startup command generation.

Phase 0: Write tests BEFORE refactoring base64 out of SSH commands.

- TestWorkerScript: exercises _WORKER_SCRIPT directly via subprocess
- TestSSHWorkerStartup: checks the SSH command generated by SSHWorker.start()
- TestSSHWorkerExecute: checks the JSON request sent by SSHWorker.execute()
"""

from __future__ import annotations

import json
import subprocess
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from imas_codex.remote.ssh_worker import _WORKER_SCRIPT, SSHWorker

# ============================================================================
# Helpers
# ============================================================================


def _run_worker_with_requests(requests: list[dict]) -> list[dict]:
    """Run _WORKER_SCRIPT with a sequence of JSON requests.

    Returns all parsed JSON lines (including the startup ``{"ready": true}``
    line as the first element).
    """
    input_lines = "\n".join(json.dumps(r) for r in requests) + "\n"
    result = subprocess.run(
        ["python3", "-c", _WORKER_SCRIPT],
        input=input_lines,
        capture_output=True,
        text=True,
        timeout=10,
    )
    responses = []
    for line in result.stdout.strip().split("\n"):
        if line.strip():
            responses.append(json.loads(line))
    return responses


# ============================================================================
# TestWorkerScript — _WORKER_SCRIPT behaviour tested directly via subprocess
# ============================================================================


class TestWorkerScript:
    """Test the _WORKER_SCRIPT Python code directly by exec'ing it in a subprocess."""

    def test_exec_runs_script_and_returns_stdout(self):
        """A script that prints should produce ok=True with the printed output."""
        responses = _run_worker_with_requests(
            [{"action": "exec", "script": "print('hello')", "stdin": "{}"}]
        )
        # responses[0] is {"ready": True, "pid": N}
        assert responses[0].get("ready") is True
        resp = responses[1]
        assert resp["ok"] is True
        assert resp["stdout"] == "hello\n"

    def test_exec_error_returns_traceback(self):
        """A script that raises should produce ok=False with error and tb fields."""
        responses = _run_worker_with_requests(
            [{"action": "exec", "script": "raise ValueError('oops')", "stdin": "{}"}]
        )
        resp = responses[1]
        assert resp["ok"] is False
        assert "oops" in resp["error"]
        assert "Traceback" in resp.get("tb", "")

    def test_ping_returns_pong(self):
        """A ping request should produce ok=True with pong=True."""
        responses = _run_worker_with_requests([{"action": "ping"}])
        resp = responses[1]
        assert resp["ok"] is True
        assert resp["pong"] is True

    def test_eof_exits_cleanly(self):
        """Closing stdin (empty input) should cause the worker to exit with code 0."""
        result = subprocess.run(
            ["python3", "-c", _WORKER_SCRIPT],
            input="",
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0

    def test_unknown_action_returns_error(self):
        """An unrecognised action should produce an error response."""
        responses = _run_worker_with_requests([{"action": "frobnicate"}])
        resp = responses[1]
        assert resp["ok"] is False
        assert "unknown action" in resp["error"].lower()

    def test_invalid_json_returns_error(self):
        """Sending garbage JSON should produce an error response (not crash)."""
        result = subprocess.run(
            ["python3", "-c", _WORKER_SCRIPT],
            input="this is not valid json\n",
            capture_output=True,
            text=True,
            timeout=10,
        )
        lines = [line for line in result.stdout.strip().split("\n") if line.strip()]
        # At least two lines: startup signal + error response
        assert len(lines) >= 2
        # The second line should report an error (not a successful parse)
        error_resp = json.loads(lines[1])
        assert error_resp["ok"] is False
        assert "invalid json" in error_resp["error"].lower()


# ============================================================================
# TestSSHWorkerStartup — SSH command construction via SSHWorker.start()
# ============================================================================


class TestSSHWorkerStartup:
    """Test the startup command generated by SSHWorker.start()."""

    async def test_startup_command_structure(self):
        """SSH command must include PATH setup and a python3 invocation."""
        with patch("asyncio.create_subprocess_exec") as mock_exec:
            mock_proc = AsyncMock()
            mock_proc.stdout = AsyncMock()
            mock_proc.stdout.readline = AsyncMock(
                return_value=json.dumps({"ready": True, "pid": 1234}).encode() + b"\n"
            )
            mock_proc.returncode = None
            mock_exec.return_value = mock_proc

            worker = SSHWorker("test-host", 0)
            await worker.start(timeout=5)

            call_args = mock_exec.call_args
            # create_subprocess_exec receives *cmd unpacked — inspect positional args
            cmd_parts = list(call_args.args)
            full_cmd = " ".join(str(p) for p in cmd_parts)

            assert "ssh" in cmd_parts[0]
            assert "test-host" in full_cmd
            assert "python3" in full_cmd
            assert "PATH" in full_cmd

    @pytest.mark.xfail(reason="base64 elimination pending - security fix", strict=False)
    async def test_no_base64_in_startup_command(self):
        """Startup command must not contain 'base64' (XDR malware trigger)."""
        with patch("asyncio.create_subprocess_exec") as mock_exec:
            mock_proc = AsyncMock()
            mock_proc.stdout = AsyncMock()
            mock_proc.stdout.readline = AsyncMock(
                return_value=json.dumps({"ready": True, "pid": 1234}).encode() + b"\n"
            )
            mock_proc.returncode = None
            mock_exec.return_value = mock_proc

            worker = SSHWorker("test-host", 0)
            await worker.start(timeout=5)

            call_args = mock_exec.call_args
            cmd_parts = list(call_args.args)
            full_cmd = " ".join(str(p) for p in cmd_parts)

            assert "base64" not in full_cmd, (
                "Startup command contains 'base64' — this triggers XDR malware "
                "detection and must be eliminated."
            )

    async def test_nice_level_applied_to_startup(self):
        """When a nice level is configured for the host, 'nice -n N' must appear."""
        from imas_codex.remote.executor import _host_nice_levels

        # Register a nice level for our test host
        _host_nice_levels["nice-host"] = 10
        try:
            with patch("asyncio.create_subprocess_exec") as mock_exec:
                mock_proc = AsyncMock()
                mock_proc.stdout = AsyncMock()
                mock_proc.stdout.readline = AsyncMock(
                    return_value=json.dumps({"ready": True, "pid": 5678}).encode()
                    + b"\n"
                )
                mock_proc.returncode = None
                mock_exec.return_value = mock_proc

                worker = SSHWorker("nice-host", 0)
                await worker.start(timeout=5)

                call_args = mock_exec.call_args
                cmd_parts = list(call_args.args)
                full_cmd = " ".join(str(p) for p in cmd_parts)

                assert "nice -n 10" in full_cmd
        finally:
            del _host_nice_levels["nice-host"]


# ============================================================================
# TestSSHWorkerExecute — JSON request protocol via SSHWorker.execute()
# ============================================================================


class TestSSHWorkerExecute:
    """Test the execute() request/response protocol."""

    def _make_alive_worker(self) -> SSHWorker:
        """Return a pre-wired SSHWorker that appears alive."""
        worker = SSHWorker("test-host", 0)
        worker._ready = True

        mock_proc = AsyncMock()
        mock_proc.returncode = None
        # stdin.write is synchronous in asyncio — use MagicMock
        mock_proc.stdin = MagicMock()
        mock_proc.stdin.write = MagicMock()
        mock_proc.stdin.drain = AsyncMock()
        worker._proc = mock_proc

        return worker

    async def test_execute_sends_script(self):
        """execute() must write a JSON line to the worker's stdin."""
        worker = self._make_alive_worker()

        ok_resp = json.dumps({"ok": True, "stdout": "done\n"}).encode() + b"\n"
        worker._proc.stdout = AsyncMock()
        worker._proc.stdout.readline = AsyncMock(return_value=ok_resp)

        await worker.execute("print('done')")

        worker._proc.stdin.write.assert_called_once()
        raw = worker._proc.stdin.write.call_args.args[0]
        payload = json.loads(raw.decode().strip())
        assert payload["action"] == "exec"
        assert "script" in payload

    async def test_execute_returns_stdout(self):
        """execute() must return the stripped stdout from the JSON response."""
        worker = self._make_alive_worker()

        ok_resp = json.dumps({"ok": True, "stdout": "hello\n"}).encode() + b"\n"
        worker._proc.stdout = AsyncMock()
        worker._proc.stdout.readline = AsyncMock(return_value=ok_resp)

        result = await worker.execute("print('hello')")
        assert result == "hello"

    async def test_execute_handles_error(self):
        """execute() must raise RuntimeError when ok=False."""
        worker = self._make_alive_worker()

        err_resp = (
            json.dumps(
                {"ok": False, "error": "NameError: x", "tb": "Traceback..."}
            ).encode()
            + b"\n"
        )
        worker._proc.stdout = AsyncMock()
        worker._proc.stdout.readline = AsyncMock(return_value=err_resp)

        with pytest.raises(RuntimeError, match="NameError"):
            await worker.execute("print(x)")

    @pytest.mark.xfail(reason="base64 elimination pending - security fix", strict=False)
    async def test_no_base64_in_exec_request(self):
        """exec request payload must not contain base64-encoded script."""
        worker = self._make_alive_worker()

        ok_resp = json.dumps({"ok": True, "stdout": ""}).encode() + b"\n"
        worker._proc.stdout = AsyncMock()
        worker._proc.stdout.readline = AsyncMock(return_value=ok_resp)

        await worker.execute("x = 1")

        raw = worker._proc.stdin.write.call_args.args[0]
        payload = json.loads(raw.decode().strip())

        # After refactoring, script should be sent as plain text, not base64
        script_field = payload.get("script", "")
        assert script_field == "x = 1", (
            f"Script is base64-encoded in the request payload: {script_field!r}. "
            "This triggers XDR malware detection and must be eliminated."
        )
