"""
IMAS Data Dictionary Knowledge Graph Pydantic Models.

AUTO-GENERATED from imas_codex/schemas/imas_dd.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-models --force
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "0.4.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "imas_dd",
        "default_range": "string",
        "description": "Graph representation of the IMAS Data Dictionary with version "
        "tracking, coordinate linking, and semantic clustering.",
        "id": "https://imas.iter.org/schemas/imas_dd",
        "imports": ["linkml:types"],
        "license": "MIT",
        "name": "imas_dd",
        "prefixes": {
            "imas": {
                "prefix_prefix": "imas",
                "prefix_reference": "https://imas.iter.org/",
            },
            "imas_dd": {
                "prefix_prefix": "imas_dd",
                "prefix_reference": "https://imas.iter.org/schemas/imas_dd/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex.worktrees/worktree-2026-01-05T11-06-45/imas_codex/schemas/imas_dd.yaml",
        "title": "IMAS Data Dictionary Knowledge Graph Schema",
    }
)


class DDDataType(str, Enum):
    """
    IMAS Data Dictionary data types
    """

    STR_0D = "STR_0D"
    """
    Scalar string
    """
    STR_1D = "STR_1D"
    """
    1D array of strings
    """
    INT_0D = "INT_0D"
    """
    Scalar integer
    """
    INT_1D = "INT_1D"
    """
    1D array of integers
    """
    INT_2D = "INT_2D"
    """
    2D array of integers
    """
    INT_3D = "INT_3D"
    """
    3D array of integers
    """
    FLT_0D = "FLT_0D"
    """
    Scalar float
    """
    FLT_1D = "FLT_1D"
    """
    1D array of floats
    """
    FLT_2D = "FLT_2D"
    """
    2D array of floats
    """
    FLT_3D = "FLT_3D"
    """
    3D array of floats
    """
    FLT_4D = "FLT_4D"
    """
    4D array of floats
    """
    FLT_5D = "FLT_5D"
    """
    5D array of floats
    """
    FLT_6D = "FLT_6D"
    """
    6D array of floats
    """
    CPX_0D = "CPX_0D"
    """
    Scalar complex
    """
    CPX_1D = "CPX_1D"
    """
    1D array of complex
    """
    CPX_2D = "CPX_2D"
    """
    2D array of complex
    """
    CPX_3D = "CPX_3D"
    """
    3D array of complex
    """
    STRUCTURE = "STRUCTURE"
    """
    Container structure (no data)
    """
    STRUCT_ARRAY = "STRUCT_ARRAY"
    """
    Array of structures
    """


class DDNodeType(str, Enum):
    """
    Time-variation character of DD nodes
    """

    dynamic = "dynamic"
    """
    Data varying in time within the IDS
    """
    constant = "constant"
    """
    Data not varying within the IDS
    """
    static = "static"
    """
    Data not varying between IDSs
    """


class PhysicsDomainDD(str, Enum):
    """
    Physics domains for IMAS data paths
    """

    equilibrium = "equilibrium"
    """
    Equilibrium reconstruction and MHD equilibrium
    """
    core_profiles = "core_profiles"
    """
    Core plasma profiles (Te, Ti, ne)
    """
    edge_profiles = "edge_profiles"
    """
    Edge and SOL plasma profiles
    """
    transport = "transport"
    """
    Transport coefficients and fluxes
    """
    mhd = "mhd"
    """
    MHD stability and instabilities
    """
    waves = "waves"
    """
    Wave heating and current drive
    """
    particles = "particles"
    """
    Energetic particles and neutrals
    """
    diagnostics = "diagnostics"
    """
    Diagnostic measurements
    """
    engineering = "engineering"
    """
    Machine and engineering systems
    """
    control = "control"
    """
    Plasma control systems
    """
    general = "general"
    """
    General/unclassified
    """


class ChangeType(str, Enum):
    """
    Types of metadata changes between DD versions
    """

    units = "units"
    """
    Units changed
    """
    documentation = "documentation"
    """
    Documentation text changed
    """
    type = "type"
    """
    Data type or node type changed
    """
    coordinates = "coordinates"
    """
    Coordinate specification changed
    """
    lifecycle = "lifecycle"
    """
    Lifecycle status changed (e.g., obsolete)
    """
    maxoccur = "maxoccur"
    """
    Maximum occurrences changed
    """


class SemanticChangeType(str, Enum):
    """
    Physics significance of documentation changes
    """

    sign_convention = "sign_convention"
    """
    Sign or orientation convention change (affects data interpretation)
    """
    coordinate_convention = "coordinate_convention"
    """
    Coordinate system or reference frame change
    """
    definition_clarification = "definition_clarification"
    """
    More precise definition without semantic change
    """
    none = "none"
    """
    No physics significance detected
    """


class DDVersion(ConfiguredBaseModel):
    """
    A version of the IMAS Data Dictionary. Versions form a chain via PREDECESSOR relationships, enabling traversal of DD evolution.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:DDVersion",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    id: str = Field(
        default=...,
        description="""Version string (e.g., \"3.42.2\", \"4.0.0\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "DDVersion",
                    "IMASPath",
                    "CoordinateSpec",
                    "SemanticCluster",
                    "PathChange",
                ],
            }
        },
    )
    release_date: datetime | None = Field(
        default=None,
        description="""Release date of this DD version""",
        json_schema_extra={
            "linkml_meta": {"alias": "release_date", "domain_of": ["DDVersion"]}
        },
    )
    is_current: bool | None = Field(
        default=None,
        description="""Whether this is the current/latest version""",
        json_schema_extra={
            "linkml_meta": {"alias": "is_current", "domain_of": ["DDVersion"]}
        },
    )
    path_count: int | None = Field(
        default=None,
        description="""Total number of paths in this version""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path_count",
                "domain_of": ["DDVersion", "IDS", "SemanticCluster"],
            }
        },
    )
    ids_count: int | None = Field(
        default=None,
        description="""Number of IDS definitions in this version""",
        json_schema_extra={
            "linkml_meta": {"alias": "ids_count", "domain_of": ["DDVersion"]}
        },
    )
    predecessor: str | None = Field(
        default=None,
        description="""Previous DD version""",
        json_schema_extra={
            "linkml_meta": {"alias": "predecessor", "domain_of": ["DDVersion"]}
        },
    )


class IDS(ConfiguredBaseModel):
    """
    A top-level Interface Data Structure definition. IDS nodes are the root containers for physics data (e.g., equilibrium, core_profiles).
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:IDS",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    name: str = Field(
        default=...,
        description="""IDS name (e.g., \"equilibrium\", \"core_profiles\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["IDS", "IMASPath", "Unit", "IdentifierSchema"],
            }
        },
    )
    description: str | None = Field(
        default=None,
        description="""IDS description from DD documentation""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["IDS", "SemanticCluster", "IdentifierSchema"],
            }
        },
    )
    physics_domain: PhysicsDomainDD | None = Field(
        default=None,
        description="""Primary physics domain""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "physics_domain",
                "domain_of": ["IDS", "IMASPath", "SemanticCluster"],
            }
        },
    )
    path_count: int | None = Field(
        default=None,
        description="""Number of paths in this IDS (current version)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path_count",
                "domain_of": ["DDVersion", "IDS", "SemanticCluster"],
            }
        },
    )
    leaf_count: int | None = Field(
        default=None,
        description="""Number of leaf nodes (data endpoints)""",
        json_schema_extra={
            "linkml_meta": {"alias": "leaf_count", "domain_of": ["IDS"]}
        },
    )
    max_depth: int | None = Field(
        default=None,
        description="""Maximum hierarchy depth""",
        json_schema_extra={"linkml_meta": {"alias": "max_depth", "domain_of": ["IDS"]}},
    )
    documentation_coverage: float | None = Field(
        default=None,
        description="""Fraction of paths with documentation (0.0-1.0)""",
        json_schema_extra={
            "linkml_meta": {"alias": "documentation_coverage", "domain_of": ["IDS"]}
        },
    )
    introduced_version: str | None = Field(
        default=None,
        description="""DD version where this IDS was introduced""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "introduced_version",
                "domain_of": ["IDS", "IMASPath"],
            }
        },
    )
    deprecated_version: str | None = Field(
        default=None,
        description="""DD version where this IDS was deprecated (null = current)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "deprecated_version",
                "domain_of": ["IDS", "IMASPath"],
            }
        },
    )


class IMASPath(ConfiguredBaseModel):
    """
    An IMAS Data Dictionary path. Represents any level from IDS root (e.g., \"equilibrium\") to leaf nodes (e.g., \"equilibrium/time_slice/boundary/psi\"). Paths form a hierarchy via PARENT relationships and link to units, coordinates, and semantic clusters. Version tracking uses INTRODUCED_IN/DEPRECATED_IN/RENAMED_TO relationships.
    This is the single authoritative representation of IMAS paths - code references should link to existing IMASPath nodes, never create them on-demand.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:IMASPath",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    id: str = Field(
        default=...,
        description="""Full path (e.g., \"equilibrium/time_slice/boundary/psi\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "DDVersion",
                    "IMASPath",
                    "CoordinateSpec",
                    "SemanticCluster",
                    "PathChange",
                ],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""Leaf name (last path component, e.g., \"psi\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["IDS", "IMASPath", "Unit", "IdentifierSchema"],
            }
        },
    )
    ids: str = Field(
        default=...,
        description="""IDS name (root of path hierarchy, e.g., \"equilibrium\")""",
        json_schema_extra={"linkml_meta": {"alias": "ids", "domain_of": ["IMASPath"]}},
    )
    documentation: str | None = Field(
        default=None,
        description="""Documentation string from DD""",
        json_schema_extra={
            "linkml_meta": {"alias": "documentation", "domain_of": ["IMASPath"]}
        },
    )
    data_type: DDDataType | None = Field(
        default=None,
        description="""Data type (e.g., FLT_1D, STR_0D, STRUCTURE)""",
        json_schema_extra={
            "linkml_meta": {"alias": "data_type", "domain_of": ["IMASPath"]}
        },
    )
    ndim: int | None = Field(
        default=None,
        description="""Number of dimensions (0-6)""",
        json_schema_extra={"linkml_meta": {"alias": "ndim", "domain_of": ["IMASPath"]}},
    )
    node_type: DDNodeType | None = Field(
        default=None,
        description="""Time-variation type (dynamic/constant/static)""",
        json_schema_extra={
            "linkml_meta": {"alias": "node_type", "domain_of": ["IMASPath"]}
        },
    )
    physics_domain: PhysicsDomainDD | None = Field(
        default=None,
        description="""Physics domain (derived from path/IDS)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "physics_domain",
                "domain_of": ["IDS", "IMASPath", "SemanticCluster"],
            }
        },
    )
    maxoccur: int | None = Field(
        default=None,
        description="""Maximum occurrences (for struct arrays)""",
        json_schema_extra={
            "linkml_meta": {"alias": "maxoccur", "domain_of": ["IMASPath"]}
        },
    )
    parent_path: str | None = Field(
        default=None,
        description="""Parent path in hierarchy (null for IDS-level paths)""",
        json_schema_extra={
            "linkml_meta": {"alias": "parent_path", "domain_of": ["IMASPath"]}
        },
    )
    unit: str | None = Field(
        default=None,
        description="""Physical units for this path""",
        json_schema_extra={"linkml_meta": {"alias": "unit", "domain_of": ["IMASPath"]}},
    )
    introduced_version: str | None = Field(
        default=None,
        description="""DD version where this path was introduced""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "introduced_version",
                "domain_of": ["IDS", "IMASPath"],
            }
        },
    )
    deprecated_version: str | None = Field(
        default=None,
        description="""DD version where this path was deprecated (null = current)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "deprecated_version",
                "domain_of": ["IDS", "IMASPath"],
            }
        },
    )
    renamed_to: str | None = Field(
        default=None,
        description="""Successor path if this was renamed (not just removed)""",
        json_schema_extra={
            "linkml_meta": {"alias": "renamed_to", "domain_of": ["IMASPath"]}
        },
    )
    identifier_schema: str | None = Field(
        default=None,
        description="""Identifier schema if this is an identifier field""",
        json_schema_extra={
            "linkml_meta": {"alias": "identifier_schema", "domain_of": ["IMASPath"]}
        },
    )


class Unit(ConfiguredBaseModel):
    """
    A physical unit used in the Data Dictionary. Units are deduplicated across all paths to enable unit-based queries.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:Unit",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    symbol: str = Field(
        default=...,
        description="""Unit symbol (e.g., \"Wb\", \"m.s^-1\", \"eV\")""",
        json_schema_extra={"linkml_meta": {"alias": "symbol", "domain_of": ["Unit"]}},
    )
    name: str | None = Field(
        default=None,
        description="""Human-readable name (e.g., \"Weber\", \"meters per second\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["IDS", "IMASPath", "Unit", "IdentifierSchema"],
            }
        },
    )
    dimension: str | None = Field(
        default=None,
        description="""Physical dimension category""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "dimension",
                "domain_of": ["Unit", "CoordinateRelationship"],
            }
        },
    )
    is_si: bool | None = Field(
        default=None,
        description="""Whether this is an SI base or derived unit""",
        json_schema_extra={"linkml_meta": {"alias": "is_si", "domain_of": ["Unit"]}},
    )


class CoordinateSpec(ConfiguredBaseModel):
    """
    An index-based coordinate specification (e.g., \"1...N\", \"1...3\"). Path references are handled via COORDINATE relationships to IMASPath.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:CoordinateSpec",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    id: str = Field(
        default=...,
        description="""Coordinate spec string (e.g., \"1...N\", \"1...3\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "DDVersion",
                    "IMASPath",
                    "CoordinateSpec",
                    "SemanticCluster",
                    "PathChange",
                ],
            }
        },
    )
    is_bounded: bool | None = Field(
        default=None,
        description="""Whether the coordinate has a fixed maximum""",
        json_schema_extra={
            "linkml_meta": {"alias": "is_bounded", "domain_of": ["CoordinateSpec"]}
        },
    )
    max_size: int | None = Field(
        default=None,
        description="""Maximum size if bounded (e.g., 3 for \"1...3\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "max_size", "domain_of": ["CoordinateSpec"]}
        },
    )


class SemanticCluster(ConfiguredBaseModel):
    """
    A semantic cluster of related IMAS paths, derived from HDBSCAN clustering on path embeddings. Paths link to clusters via IN_CLUSTER.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:SemanticCluster",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    id: str = Field(
        default=...,
        description="""Cluster identifier (e.g., \"cluster_42\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "DDVersion",
                    "IMASPath",
                    "CoordinateSpec",
                    "SemanticCluster",
                    "PathChange",
                ],
            }
        },
    )
    label: str = Field(
        default=...,
        description="""LLM-generated semantic label (e.g., \"boundary geometry\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "label", "domain_of": ["SemanticCluster"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Extended description of the cluster concept""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["IDS", "SemanticCluster", "IdentifierSchema"],
            }
        },
    )
    physics_domain: PhysicsDomainDD | None = Field(
        default=None,
        description="""Primary physics domain of cluster members""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "physics_domain",
                "domain_of": ["IDS", "IMASPath", "SemanticCluster"],
            }
        },
    )
    path_count: int | None = Field(
        default=None,
        description="""Number of paths in this cluster""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path_count",
                "domain_of": ["DDVersion", "IDS", "SemanticCluster"],
            }
        },
    )
    cross_ids: bool | None = Field(
        default=None,
        description="""Whether cluster spans multiple IDS""",
        json_schema_extra={
            "linkml_meta": {"alias": "cross_ids", "domain_of": ["SemanticCluster"]}
        },
    )
    representative_path: str | None = Field(
        default=None,
        description="""Most central path (closest to centroid)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "representative_path",
                "domain_of": ["SemanticCluster"],
            }
        },
    )


class IdentifierSchema(ConfiguredBaseModel):
    """
    An enumeration/identifier schema from the Data Dictionary. Options are stored as JSON property rather than separate nodes.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:IdentifierSchema",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    name: str = Field(
        default=...,
        description="""Schema name (e.g., \"coordinate_identifier\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["IDS", "IMASPath", "Unit", "IdentifierSchema"],
            }
        },
    )
    description: str | None = Field(
        default=None,
        description="""Schema description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["IDS", "SemanticCluster", "IdentifierSchema"],
            }
        },
    )
    option_count: int | None = Field(
        default=None,
        description="""Number of valid options""",
        json_schema_extra={
            "linkml_meta": {"alias": "option_count", "domain_of": ["IdentifierSchema"]}
        },
    )
    options: str | None = Field(
        default=None,
        description="""JSON-encoded list of {index, name, description}""",
        json_schema_extra={
            "linkml_meta": {"alias": "options", "domain_of": ["IdentifierSchema"]}
        },
    )


class PathChange(ConfiguredBaseModel):
    """
    Records a change to path metadata between DD versions. Enables tracking of documentation updates, unit changes, etc.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:PathChange",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    id: str = Field(
        default=...,
        description="""Composite key (path:change_type:version)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "DDVersion",
                    "IMASPath",
                    "CoordinateSpec",
                    "SemanticCluster",
                    "PathChange",
                ],
            }
        },
    )
    change_type: ChangeType = Field(
        default=...,
        description="""Type of change""",
        json_schema_extra={
            "linkml_meta": {"alias": "change_type", "domain_of": ["PathChange"]}
        },
    )
    old_value: str | None = Field(
        default=None,
        description="""Previous value (as string)""",
        json_schema_extra={
            "linkml_meta": {"alias": "old_value", "domain_of": ["PathChange"]}
        },
    )
    new_value: str | None = Field(
        default=None,
        description="""New value (as string)""",
        json_schema_extra={
            "linkml_meta": {"alias": "new_value", "domain_of": ["PathChange"]}
        },
    )
    semantic_type: SemanticChangeType | None = Field(
        default=None,
        description="""Physics significance (for documentation changes)""",
        json_schema_extra={
            "linkml_meta": {"alias": "semantic_type", "domain_of": ["PathChange"]}
        },
    )
    keywords_detected: str | None = Field(
        default=None,
        description="""JSON array of significant keywords found in new value""",
        json_schema_extra={
            "linkml_meta": {"alias": "keywords_detected", "domain_of": ["PathChange"]}
        },
    )
    path: str = Field(
        default=...,
        description="""The path that changed""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["PathChange", "ClusterMembership"],
            }
        },
    )
    version: str = Field(
        default=...,
        description="""Version where the change occurred""",
        json_schema_extra={
            "linkml_meta": {"alias": "version", "domain_of": ["PathChange"]}
        },
    )


class CoordinateRelationship(ConfiguredBaseModel):
    """
    Represents a coordinate relationship between an IMASPath and its coordinate (either another IMASPath or a CoordinateSpec). Stored as relationship properties.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:CoordinateRelationship",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    dimension: int = Field(
        default=...,
        description="""Which dimension this coordinate applies to (1-6)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "dimension",
                "domain_of": ["Unit", "CoordinateRelationship"],
            }
        },
    )
    alternative: bool | None = Field(
        default=None,
        description="""Whether this is an OR alternative coordinate""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "alternative",
                "domain_of": ["CoordinateRelationship"],
            }
        },
    )
    same_as: bool | None = Field(
        default=None,
        description="""Whether from coordinate_same_as attribute""",
        json_schema_extra={
            "linkml_meta": {"alias": "same_as", "domain_of": ["CoordinateRelationship"]}
        },
    )
    source_path: str = Field(
        default=...,
        description="""The path that has this coordinate""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source_path",
                "domain_of": ["CoordinateRelationship"],
            }
        },
    )
    target_path: str | None = Field(
        default=None,
        description="""The coordinate path (for path references)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "target_path",
                "domain_of": ["CoordinateRelationship"],
            }
        },
    )
    target_spec: str | None = Field(
        default=None,
        description="""The coordinate spec (for index coordinates)""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "target_spec",
                "domain_of": ["CoordinateRelationship"],
            }
        },
    )


class ClusterMembership(ConfiguredBaseModel):
    """
    Represents membership of an IMASPath in a SemanticCluster. Distance indicates proximity to cluster centroid.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas_dd:ClusterMembership",
            "from_schema": "https://imas.iter.org/schemas/imas_dd",
        }
    )

    path: str = Field(
        default=...,
        description="""The member path""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": ["PathChange", "ClusterMembership"],
            }
        },
    )
    cluster: str = Field(
        default=...,
        description="""The cluster""",
        json_schema_extra={
            "linkml_meta": {"alias": "cluster", "domain_of": ["ClusterMembership"]}
        },
    )
    distance: float | None = Field(
        default=None,
        description="""Distance to cluster centroid (lower = more central)""",
        json_schema_extra={
            "linkml_meta": {"alias": "distance", "domain_of": ["ClusterMembership"]}
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
DDVersion.model_rebuild()
IDS.model_rebuild()
IMASPath.model_rebuild()
Unit.model_rebuild()
CoordinateSpec.model_rebuild()
SemanticCluster.model_rebuild()
IdentifierSchema.model_rebuild()
PathChange.model_rebuild()
CoordinateRelationship.model_rebuild()
ClusterMembership.model_rebuild()
