"""
Facility Knowledge Graph Pydantic Models.

AUTO-GENERATED from imas_codex/schemas/facility.yaml
DO NOT EDIT THIS FILE DIRECTLY - edit the LinkML schema instead.

To regenerate:
    uv run build-models --force
"""

from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, RootModel

metamodel_version = "None"
version = "0.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "facility",
        "default_range": "string",
        "description": "Unified schema for capturing all knowledge about fusion "
        "research facilities, including data infrastructure, computing "
        "environment, available tools, diagnostic systems, analysis "
        "codes, and IMAS data mappings.",
        "id": "https://imas.iter.org/schemas/facility",
        "imports": ["linkml:types"],
        "license": "MIT",
        "name": "facility",
        "prefixes": {
            "facility": {
                "prefix_prefix": "facility",
                "prefix_reference": "https://imas.iter.org/schemas/facility/",
            },
            "imas": {
                "prefix_prefix": "imas",
                "prefix_reference": "https://imas.iter.org/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "/home/ITER/mcintos/Code/imas-codex/imas_codex/schemas/facility.yaml",
        "title": "Fusion Facility Knowledge Graph Schema",
    }
)


class TreeNodeType(str, Enum):
    """
    MDSplus node data types
    """

    STRUCTURE = "STRUCTURE"
    """
    Container node with no data
    """
    SIGNAL = "SIGNAL"
    """
    Time-varying measurement data
    """
    NUMERIC = "NUMERIC"
    """
    Numeric scalar or array
    """
    TEXT = "TEXT"
    """
    Text/string data
    """
    AXIS = "AXIS"
    """
    Coordinate axis data
    """
    SUBTREE = "SUBTREE"
    """
    Reference to another tree
    """
    ACTION = "ACTION"
    """
    Action sequence node
    """
    DISPATCH = "DISPATCH"
    """
    Dispatch scheduling node
    """
    TASK = "TASK"
    """
    Task definition node
    """


class DiagnosticCategory(str, Enum):
    """
    Categories of fusion plasma diagnostics
    """

    magnetics = "magnetics"
    """
    Magnetic field and flux measurements
    """
    spectroscopy = "spectroscopy"
    """
    Spectroscopic diagnostics (visible, UV, X-ray)
    """
    particle = "particle"
    """
    Particle diagnostics (CX, NPA, beam emission)
    """
    imaging = "imaging"
    """
    Camera and imaging systems
    """
    microwave = "microwave"
    """
    Microwave diagnostics (ECE, reflectometry)
    """
    bolometry = "bolometry"
    """
    Radiated power measurements
    """
    neutron = "neutron"
    """
    Neutron flux and spectrum diagnostics
    """
    probe = "probe"
    """
    Langmuir probes and other insertable probes
    """
    interferometry = "interferometry"
    """
    Interferometric density measurements
    """
    thomson = "thomson"
    """
    Thomson scattering systems
    """


class AnalysisCodeType(str, Enum):
    """
    Types of physics analysis codes
    """

    equilibrium = "equilibrium"
    """
    Equilibrium reconstruction (EFIT, LIUQE, CLISTE)
    """
    transport = "transport"
    """
    Transport analysis (ASTRA, TRANSP, JETTO)
    """
    mhd = "mhd"
    """
    MHD stability analysis
    """
    heating = "heating"
    """
    Heating deposition codes (TORAY, TORBEAM, NUBEAM)
    """
    control = "control"
    """
    Real-time plasma control systems
    """
    profile_fitting = "profile_fitting"
    """
    Profile fitting and kinetic analysis
    """
    integrated = "integrated"
    """
    Integrated modeling workflows
    """


class ServerRole(str, Enum):
    """
    Role of a data server in the facility infrastructure
    """

    primary = "primary"
    """
    Main production data server
    """
    secondary = "secondary"
    """
    Backup or read-replica server
    """
    legacy = "legacy"
    """
    Historical/archived data server
    """
    realtime = "realtime"
    """
    Real-time control system data
    """
    analysis = "analysis"
    """
    Analysis results server
    """


class ToolCategory(str, Enum):
    """
    Categories of command-line tools
    """

    search = "search"
    """
    Search tools (rg, ag, grep, find)
    """
    text = "text"
    """
    Text processing (awk, sed, jq)
    """
    file = "file"
    """
    File utilities (tree, file, stat)
    """
    editor = "editor"
    """
    Text editors (vim, nano, emacs)
    """
    vcs = "vcs"
    """
    Version control (git, svn)
    """
    network = "network"
    """
    Network tools (wget, curl, rsync, ssh)
    """
    build = "build"
    """
    Build tools (make, cmake, ninja)
    """
    compiler = "compiler"
    """
    Compilers (gcc, gfortran, icc)
    """
    mpi = "mpi"
    """
    MPI tools (mpirun, mpicc, srun)
    """
    scheduler = "scheduler"
    """
    Job schedulers (sbatch, qsub)
    """
    data = "data"
    """
    Data tools (h5dump, ncdump, mdstcl)
    """
    python = "python"
    """
    Python tools (pip, conda, jupyter)
    """
    other = "other"
    """
    Other/uncategorized tools
    """


class DataFormatType(str, Enum):
    """
    Types of data storage formats
    """

    mdsplus = "mdsplus"
    """
    MDSplus tree-based storage
    """
    hdf5 = "hdf5"
    """
    HDF5 hierarchical data format
    """
    netcdf = "netcdf"
    """
    NetCDF scientific data format
    """
    csv = "csv"
    """
    Comma-separated values
    """
    json = "json"
    """
    JSON data files
    """
    mat = "mat"
    """
    MATLAB .mat files
    """
    idl = "idl"
    """
    IDL save files
    """
    imas = "imas"
    """
    IMAS data format
    """


class Facility(ConfiguredBaseModel):
    """
    A fusion research facility. Root node for all facility-specific knowledge.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:Facility",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        description="""Unique facility identifier (e.g., \"epfl\", \"iter\", \"jet\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""Human-readable facility name (e.g., \"EPFL/TCV\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    ssh_host: str | None = Field(
        default=None,
        description="""SSH host alias for remote access""",
        json_schema_extra={
            "linkml_meta": {"alias": "ssh_host", "domain_of": ["Facility"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Facility description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    machine: str | None = Field(
        default=None,
        description="""Tokamak/stellarator name (e.g., \"TCV\", \"ITER\", \"JET\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "machine", "domain_of": ["Facility"]}
        },
    )
    location: str | None = Field(
        default=None,
        description="""Geographic location""",
        json_schema_extra={
            "linkml_meta": {"alias": "location", "domain_of": ["Facility"]}
        },
    )


class DataServer(ConfiguredBaseModel):
    """
    A data server providing access to experimental data
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "abstract": True,
            "class_uri": "facility:DataServer",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    hostname: str = Field(
        default=...,
        description="""Server hostname""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "hostname",
                "domain_of": ["DataServer", "MDSplusServer"],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    role: ServerRole | None = Field(
        default=None,
        description="""Server role in the infrastructure""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "role",
                "domain_of": ["DataServer", "MDSplusServer"],
            }
        },
    )
    description: str | None = Field(
        default=None,
        description="""Server description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )


class MDSplusServer(DataServer):
    """
    An MDSplus data server
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:MDSplusServer",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    hostname: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "hostname",
                "domain_of": ["DataServer", "MDSplusServer"],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    role: ServerRole | None = Field(
        default=None,
        json_schema_extra={
            "linkml_meta": {
                "alias": "role",
                "domain_of": ["DataServer", "MDSplusServer"],
            }
        },
    )
    port: int | None = Field(
        default=None,
        description="""MDSplus port (default 8000)""",
        json_schema_extra={
            "linkml_meta": {"alias": "port", "domain_of": ["MDSplusServer"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Server description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )


class MDSplusTree(ConfiguredBaseModel):
    """
    An MDSplus tree (hierarchical data container)
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:MDSplusTree",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    name: str = Field(
        default=...,
        description="""Tree name (e.g., \"tcv_shot\", \"results\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    server_hostname: str | None = Field(
        default=None,
        description="""Primary server hosting this tree""",
        json_schema_extra={
            "linkml_meta": {"alias": "server_hostname", "domain_of": ["MDSplusTree"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Tree description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    shot_dependent: bool | None = Field(
        default=True,
        description="""Whether tree structure varies by shot""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "shot_dependent",
                "domain_of": ["MDSplusTree"],
                "ifabsent": "true",
            }
        },
    )


class TreeNode(ConfiguredBaseModel):
    """
    A node within an MDSplus tree
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:TreeNode",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    path: str = Field(
        default=...,
        description="""Full node path (e.g., \"\\RESULTS::LIUQE:IP\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    tree_name: str = Field(
        default=...,
        description="""Parent tree name""",
        json_schema_extra={
            "linkml_meta": {"alias": "tree_name", "domain_of": ["TreeNode"]}
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    node_type: TreeNodeType | None = Field(
        default=None,
        description="""MDSplus node data type""",
        json_schema_extra={
            "linkml_meta": {"alias": "node_type", "domain_of": ["TreeNode"]}
        },
    )
    units: str | None = Field(
        default=None,
        description="""Physical units (SI)""",
        json_schema_extra={
            "linkml_meta": {"alias": "units", "domain_of": ["TreeNode", "IMASPath"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Node description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    example_shot: int | None = Field(
        default=None,
        description="""Example shot number where this node exists""",
        json_schema_extra={
            "linkml_meta": {"alias": "example_shot", "domain_of": ["TreeNode"]}
        },
    )


class TDIFunction(ConfiguredBaseModel):
    """
    A TDI (Tree Data Interface) function providing high-level data access.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:TDIFunction",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    name: str = Field(
        default=...,
        description="""Function name (e.g., \"tcv_eq\", \"tcv_ip\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    file_path: str | None = Field(
        default=None,
        description="""Path to the .fun file""",
        json_schema_extra={
            "linkml_meta": {"alias": "file_path", "domain_of": ["TDIFunction"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Function description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    parameters: list[str] | None = Field(
        default=None,
        description="""Function parameter names""",
        json_schema_extra={
            "linkml_meta": {"alias": "parameters", "domain_of": ["TDIFunction"]}
        },
    )
    return_type: str | None = Field(
        default=None,
        description="""Return type description""",
        json_schema_extra={
            "linkml_meta": {"alias": "return_type", "domain_of": ["TDIFunction"]}
        },
    )
    accesses: list[str] | None = Field(
        default=None,
        description="""TreeNodes this function reads""",
        json_schema_extra={
            "linkml_meta": {"alias": "accesses", "domain_of": ["TDIFunction"]}
        },
    )
    calls: list[str] | None = Field(
        default=None,
        description="""Other TDI functions this function calls""",
        json_schema_extra={
            "linkml_meta": {"alias": "calls", "domain_of": ["TDIFunction"]}
        },
    )


class DataLocation(ConfiguredBaseModel):
    """
    A location where data files are stored
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:DataLocation",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    path: str = Field(
        default=...,
        description="""Filesystem path""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    format: DataFormatType | None = Field(
        default=None,
        description="""Primary data format at this location""",
        json_schema_extra={
            "linkml_meta": {"alias": "format", "domain_of": ["DataLocation"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""What data is stored here""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    naming_pattern: str | None = Field(
        default=None,
        description="""File naming convention (e.g., \"shot_{shot}.h5\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "naming_pattern", "domain_of": ["DataLocation"]}
        },
    )


class ShotRange(ConfiguredBaseModel):
    """
    A range of shot numbers with common characteristics
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:ShotRange",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    name: str | None = Field(
        default=None,
        description="""Name or description of this range""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    start_shot: int | None = Field(
        default=None,
        description="""First shot number""",
        json_schema_extra={
            "linkml_meta": {"alias": "start_shot", "domain_of": ["ShotRange"]}
        },
    )
    end_shot: int | None = Field(
        default=None,
        description="""Last shot number (null if ongoing)""",
        json_schema_extra={
            "linkml_meta": {"alias": "end_shot", "domain_of": ["ShotRange"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""What this shot range represents (e.g., \"H-mode campaign 2024\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )


class PythonEnvironment(ConfiguredBaseModel):
    """
    A Python installation on the facility
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:PythonEnvironment",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    version: str = Field(
        default=...,
        description="""Python version (e.g., \"3.9.21\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "AnalysisCode",
                ],
            }
        },
    )
    path: str = Field(
        default=...,
        description="""Path to Python executable""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    is_default: bool | None = Field(
        default=None,
        description="""Whether this is the default Python""",
        json_schema_extra={
            "linkml_meta": {"alias": "is_default", "domain_of": ["PythonEnvironment"]}
        },
    )
    packages: list[str] | None = Field(
        default=None,
        description="""Installed packages (format \"name==version\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "packages", "domain_of": ["PythonEnvironment"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Notes about this Python environment""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


class OperatingSystem(ConfiguredBaseModel):
    """
    Operating system information for a facility
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:OperatingSystem",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""OS distribution name (e.g., \"RHEL\", \"Ubuntu\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    version: str = Field(
        default=...,
        description="""OS version (e.g., \"9.6\", \"22.04\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "AnalysisCode",
                ],
            }
        },
    )
    kernel: str | None = Field(
        default=None,
        description="""Kernel version string""",
        json_schema_extra={
            "linkml_meta": {"alias": "kernel", "domain_of": ["OperatingSystem"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Notes about the operating system""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


class Compiler(ConfiguredBaseModel):
    """
    A compiler available at the facility
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:Compiler",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""Compiler name (e.g., \"gcc\", \"gfortran\", \"ifort\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    version: str | None = Field(
        default=None,
        description="""Compiler version""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "AnalysisCode",
                ],
            }
        },
    )
    path: str | None = Field(
        default=None,
        description="""Path to compiler executable""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Notes about this compiler""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


class ModuleSystem(ConfiguredBaseModel):
    """
    Environment module system (Lmod, Environment Modules)
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:ModuleSystem",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    available: bool = Field(
        default=...,
        description="""Whether a module system is available""",
        json_schema_extra={
            "linkml_meta": {"alias": "available", "domain_of": ["ModuleSystem", "Tool"]}
        },
    )
    type: str | None = Field(
        default=None,
        description="""Module system type (e.g., \"lmod\", \"environment-modules\")""",
        json_schema_extra={
            "linkml_meta": {"alias": "type", "domain_of": ["ModuleSystem"]}
        },
    )
    default_modules: list[str] | None = Field(
        default=None,
        description="""Modules loaded by default""",
        json_schema_extra={
            "linkml_meta": {"alias": "default_modules", "domain_of": ["ModuleSystem"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Notes about the module system""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


class Tool(ConfiguredBaseModel):
    """
    A command-line tool available at the facility
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:Tool",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""Tool name (e.g., \"rg\", \"h5dump\", \"git\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    available: bool = Field(
        default=...,
        description="""Whether the tool is installed and accessible""",
        json_schema_extra={
            "linkml_meta": {"alias": "available", "domain_of": ["ModuleSystem", "Tool"]}
        },
    )
    path: str | None = Field(
        default=None,
        description="""Path to the tool executable""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    version: str | None = Field(
        default=None,
        description="""Tool version string""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "AnalysisCode",
                ],
            }
        },
    )
    category: ToolCategory | None = Field(
        default=None,
        description="""Tool category""",
        json_schema_extra={
            "linkml_meta": {"alias": "category", "domain_of": ["Tool", "Diagnostic"]}
        },
    )
    notes: list[str] | None = Field(
        default=None,
        description="""Notes about this tool""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


class Diagnostic(ConfiguredBaseModel):
    """
    A plasma diagnostic system
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:Diagnostic",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    name: str = Field(
        default=...,
        description="""Diagnostic name (e.g., \"Thomson\", \"ECE\", \"MSE\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    category: DiagnosticCategory | None = Field(
        default=None,
        description="""Diagnostic category""",
        json_schema_extra={
            "linkml_meta": {"alias": "category", "domain_of": ["Tool", "Diagnostic"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Diagnostic description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    writes_to: list[str] | None = Field(
        default=None,
        description="""TreeNodes this diagnostic writes data to""",
        json_schema_extra={
            "linkml_meta": {"alias": "writes_to", "domain_of": ["Diagnostic"]}
        },
    )


class AnalysisCode(ConfiguredBaseModel):
    """
    A physics analysis or simulation code
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:AnalysisCode",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    name: str = Field(
        default=...,
        description="""Code name (e.g., \"LIUQE\", \"ASTRA\", \"TORAY\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Facility",
                    "MDSplusTree",
                    "TDIFunction",
                    "ShotRange",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                ],
            }
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    code_type: AnalysisCodeType | None = Field(
        default=None,
        description="""Type of analysis""",
        json_schema_extra={
            "linkml_meta": {"alias": "code_type", "domain_of": ["AnalysisCode"]}
        },
    )
    description: str | None = Field(
        default=None,
        description="""Code description""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    version: str | None = Field(
        default=None,
        description="""Code version if known""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "version",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "Tool",
                    "AnalysisCode",
                ],
            }
        },
    )
    container_path: str | None = Field(
        default=None,
        description="""Path to container image if applicable""",
        json_schema_extra={
            "linkml_meta": {"alias": "container_path", "domain_of": ["AnalysisCode"]}
        },
    )
    produces: list[str] | None = Field(
        default=None,
        description="""TreeNodes this code produces data for""",
        json_schema_extra={
            "linkml_meta": {"alias": "produces", "domain_of": ["AnalysisCode"]}
        },
    )


class IMASPath(ConfiguredBaseModel):
    """
    An IMAS data dictionary path
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "imas:Path",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    path: str = Field(
        default=...,
        description="""Full IMAS path (e.g., \"equilibrium/time_slice/boundary/psi\")""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "path",
                "domain_of": [
                    "TreeNode",
                    "DataLocation",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASPath",
                ],
            }
        },
    )
    ids: str = Field(
        default=...,
        description="""IDS name (e.g., \"equilibrium\", \"core_profiles\")""",
        json_schema_extra={"linkml_meta": {"alias": "ids", "domain_of": ["IMASPath"]}},
    )
    description: str | None = Field(
        default=None,
        description="""Path description from IMAS DD""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Facility",
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASPath",
                ],
            }
        },
    )
    units: str | None = Field(
        default=None,
        description="""Physical units from IMAS DD""",
        json_schema_extra={
            "linkml_meta": {"alias": "units", "domain_of": ["TreeNode", "IMASPath"]}
        },
    )


class IMASMapping(ConfiguredBaseModel):
    """
    A mapping from facility-specific data to IMAS
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "class_uri": "facility:IMASMapping",
            "from_schema": "https://imas.iter.org/schemas/facility",
        }
    )

    id: str = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "alias": "id",
                "domain_of": [
                    "Facility",
                    "ShotRange",
                    "PythonEnvironment",
                    "Compiler",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )
    source_path: str = Field(
        default=...,
        description="""Source path (TreeNode or TDI function)""",
        json_schema_extra={
            "linkml_meta": {"alias": "source_path", "domain_of": ["IMASMapping"]}
        },
    )
    target_path: str = Field(
        default=...,
        description="""Target IMAS path""",
        json_schema_extra={
            "linkml_meta": {"alias": "target_path", "domain_of": ["IMASMapping"]}
        },
    )
    facility_id: str = Field(
        default=...,
        description="""Parent facility ID""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "facility_id",
                "domain_of": [
                    "DataServer",
                    "MDSplusServer",
                    "MDSplusTree",
                    "TreeNode",
                    "TDIFunction",
                    "DataLocation",
                    "ShotRange",
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "Diagnostic",
                    "AnalysisCode",
                    "IMASMapping",
                ],
            }
        },
    )
    transformation: str | None = Field(
        default=None,
        description="""Transformation expression (e.g., unit conversion)""",
        json_schema_extra={
            "linkml_meta": {"alias": "transformation", "domain_of": ["IMASMapping"]}
        },
    )
    validated: bool | None = Field(
        default=None,
        description="""Whether this mapping has been validated""",
        json_schema_extra={
            "linkml_meta": {"alias": "validated", "domain_of": ["IMASMapping"]}
        },
    )
    notes: str | None = Field(
        default=None,
        description="""Mapping notes""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "notes",
                "domain_of": [
                    "PythonEnvironment",
                    "OperatingSystem",
                    "Compiler",
                    "ModuleSystem",
                    "Tool",
                    "IMASMapping",
                ],
            }
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Facility.model_rebuild()
DataServer.model_rebuild()
MDSplusServer.model_rebuild()
MDSplusTree.model_rebuild()
TreeNode.model_rebuild()
TDIFunction.model_rebuild()
DataLocation.model_rebuild()
ShotRange.model_rebuild()
PythonEnvironment.model_rebuild()
OperatingSystem.model_rebuild()
Compiler.model_rebuild()
ModuleSystem.model_rebuild()
Tool.model_rebuild()
Diagnostic.model_rebuild()
AnalysisCode.model_rebuild()
IMASPath.model_rebuild()
IMASMapping.model_rebuild()
